SimCityChat = {}

SimCityChat.chatCollection = {

	"Chµ, ®«ng qu¸ nhØ!",

	"ThÌm ¨n kÑo hå l« qu¸ :L",

	"§õng chäc tao",

	"Mî nã, hÕt tiÒn råi",

	"Hey, cho em İt vµng",

	"¦íc g× m×nh cã con ChiÕu D¹",

	"£ mµi, g¸i k×a",

	"Tui ®Ñp qu¸ mµ",

	"Chót xİu ®i s¨n boss HK ko?",

	"N­íc s«i! N­íc s«i",

	"§Ñp trai cã g× sai",

	"¦íc g× m×nh cã bå nhØ",

	"Th»ng An thiÕu tiÒn ch­a tr¶",

	"Kú nµy kĞo héi ®¸nh nã míi ®­îc",

	"Th»ng kia cã tiÒn ®Êy",

	"Trèn ®»ng nµo víi «ng",

	"H«m nay trêi m¸t nhØ",

	"Qu¸n ch¸o lßng ngon qu¸ :)",

	"Th»ng nµo ®¸nh lĞn tao :@",

	"ks = ds",

	"Dang ra! Dang ra!",

	"Kh«ng biÕt quan binh ë ®©u",

	"C« n­¬ng kia xinh thËt",

	"ña g× d¹",

	"Hñ tiÕu ngon nhØ",

	"T­¬ng D­¬ng nµy cã g× vui?",

	"§õng ®Ó tao gÆp :@",

	"T«i bŞ mãc tói råi :L",

	"HÕt tiÒn råi sao giê?",

	"§­êng xa mÖt qu¸",

	"TiÖm vò khİ ë ®©u nhØ ?",

	"Lµm sao luyÖn skill ta?",

	"Nghe nãi D­¬ng Ch©u ®ang m­a",

	"M×nh bŞ bÖnh råi",

	"Thµnh §« L©m An §¹i Lı ta t×m nµng",

	"T×m em gi÷a D­¬ng Ch©u chiÒu m­a",

	"§i ®u ®­a ®i",

	"Con Siªu Quang kia ®Ñp qu¸",

	"Bé HKMP kia vip nhØ",

	"Ğp 6 dßng mµ xŞt hoµi :L",

	"§¸nh hoµi kh«ng th¾ng næi",

	"Mua vâ l©m mËt tŞch ®©y!!!!",

	"Ai b¸n bk NMC ko?",

	"B¸n Thñy Tinh ®©y!!!",

	"ThÌm n­íc mİa qu¸!!!",

	"Nguy hiÓm! Ch¹y lÑ!",

	"T«i kh«ng thÓ h¸t live!",

	"Buån lµm chi em ¬i !",

	"Ai ve chai dĞp ®øt thao nh«m b¸n h«n ?",

	"Xin ®õng h«n t«i",

	"Tao ghim nã n·y giê",

	"Hay lµ m×nh giËt tiÒn nã nhØ",

	"Mïa ®µo n¨m nay ®Ñp thËt",

	"L¹i hÕt tiÒn råi",

	"Nha m«n th¸ng nµy ch­a ph¸t l­¬ng",

	"Qu¸n trµ ¤ Long thËt nh¹t nhÏo",

	"§­êng h«m nay v¾ng c¸c c« n­¬ng nhØ",

	"Nghe nãi LiÔu Thanh Thanh ®ang ë gÇn ®©y",

	"H×nh nh­ HuyÒn Gi¸c §¹i S­ míi võa ®i qua",

	"Cã nªn c­íp nha m«n kh«ng nhØ ?",

	"T×nh h×nh Tèng Kim cã vÎ c¨ng ®©y",

	"Giang hå ®ån r»ng cã kÎ thµnh lËp ¸c Nh©n Cèc",

	"ThÌm b¸nh bao qu¸",

	"§au bông qu¸",

	"§µo cña nhá kia bù ghª mµi",

	"C« n­¬ng µ, cho sê c¸i Êy ®­îc khum?",

	"M×nh thiÖt lµ biÕn th¸i mµ, hİ hİ hİ",

	"¡n dĞp kh«ng?",

	"§å khã ­a",

	"TiÓu nhŞ, tİnh tiÒn!",

	"§Ëu xanh rau muèng nã",

	"Yªu em lµ anh sai",

	"MÑ ¬i, con muèn lÊy nhá kia",

	"D¹o nµy nghÌo qu¸",

	"Con g¸i s¸ng n¾ng, chiÒu m­a",

	"T×nh lµ bôi, phñi lµ bay",

	"D©n ch¬i th× sî mÌo g× m­a r¬i",

	"Yªu véi lµ ngu vl",

	"M¸ dÆn cßn nhá kh«ng cho yªu",

	"Bít cµ khŞa ®i nha",

	"Nhan s¾c cã h¹n, thñ ®o¹n th× cã thõa",

	"TiÒn kh«ng ph¶i lµ tÊt c¶ nha",

	"Sai th× söa, mµ chöa th× ®Î...",

	"Muèn thµnh cao thñ, nhÊt ®Şnh ph¶i cµy ®ªm",

	"Mua kİch HSL >5% ®©yyyy",

	"Ai b¸n phi phong pmmmmm",

	"ChiÒu ®i c©u c¸ kh«ng mµi",

	"TuyÓn ng­êi vµo bang",

	"Cßn tiÒn kh«ng? Cho tau vay İt ®i",

	"Tèi nay nhËu nha!",

	"§au bao tö qu¸, lµm sao giê",

	"§«i khi muèn giÕt th»ng ®Ñp trai nhÊt thÕ giíi",

	"M¾c ãi ghª!",

	"B¸nh bao ®i c« b¸c ¬i",

	"Hihihi!",

	"Tao cßn cã 5Kv µ",

	"Míi bŞ bå t¸t vµo mÆt, huhuhu",

	"Tui khæ qu¸ mµ",

	"§ang thÊt t×nh",

	"Tèi nay ¨n c¬m víi c¸",

	"Tèi nay ¨n c¬m víi trøng",

	"Lµm 1 xŞ kh«ng mµi",

	"HÕ l«!",

	"H¸t mét bµi nghe ch¬i ®i!",

	"ó lµ la",

	"Nghe nãi T­¬ng D­¬ng cã héi chî",

	"TiÒn ®©u mµ n¹p ®©y",

	"Trêi l¹nh qu¸",

	"B©y giê ph¶i lµm sao, haizz",

	"Haizzzz!!!",

	"Tau ®i b¸o quan",

	"§ãi bông ghª",

	"Tr¸nh ra, ng­êi yªu kiu tau vÒ gÊp",

	"Lµm nh¸y ®i mµ",

	"Kh«ng sî chã",

	"Loa loa loa, mÊt hÕt c¸i loa",

	"M¸u cña tau İt qu¸, sèc dame",

	"Ngon th× ra Nam BiÖn Kinh móc nhau nÌ",

	"Mua nhÉn hÖ méc kh¸ng cao, ai cã pm",

	"C« ®¬n qu¸",

	"C«n L«n cã g¸i ®Ñp!",

	"Pty em víiiiii",

	"§au bông qu¸",

	"§­êng nµo ®i L©m Du Quan vËy?",

	"Tau ®i s¨n boss s¸t thñ råi",

	"B¸n d©y chuyÒn KTC 18, ai quan t©m pm",

	"B¸n giµy tèc ®é 40 - hÖ thæ, 1k2v!!!",

	"Mua bİ kİp C¸i Bang Rång, ai cã hó em c¸iiii",

	"Mua ¤ V©n §¹p TuyÕt!",

	"Mua §­êng NghÖ Gi¸p ngon, hÖ Thæ",

	"Mua bao tay nam hÖ Háa, PTVL > 15%",

	"Hång nhan häa thñy",

	"Nî nÇng chång chÊt, huhuhu",

	"Tèng Kim k×a!",

	"Mua tiÒn vµng SLL, ai b¸n hó em",

	"T×nh yªu kh«ng cã lçi, lçi do tau xÊu",

	"D· TÈu kh¾m vl",

	"VÒ Thµnh §« T©y giao dŞch!",

	"B¸c sÜ b¶o c­íi",

	"Lªn M¹c Cao QuËt train ®i",

	"Sa M¹c 3 ®ång ng­êi qu¸, ®æi chç kh¸c",

	"Con TVB kia nã qu¸nh em",

	"§óng råi",

	"Tèi ®i ¨n èc kh«ng?",

	"Tau hÕt tiÒn råi",

	"Lµ l¸ la",

	"§å con ng­êi ¸c ®éc",

	"§å m¸u l¹nh",

	"Tau ®i b¸o quan",

	"HÕt thæ ®Şa phï råi",

	"ChÕt cha, quªn mua Thæ §Şa Phï",

	"Anh ¬i, cho em İt tiÒn ®i xa phu víi",

	"T×m s­ phô, høa sÏ ngoan",

	"T×m ng­êi yªu",

	"Chót n÷a b¸o danh bªn Tèng nha",

	"Tau ®i bªn Kim",

	"Nhí em!",

	"Nhí anh!",

	"Cuéc ®êi sÏ l¹c tr«i vÒ ®©u?",

	"Tr¸nh ®­êng cho quan",

	"C­êi xÊu vl",

	"Trêi ¬i lµ trêi",

	"Xu cµ na råi",

	"NghÌo cßn h¬n con mÌo n÷a, hic",

	"¦íc g× anh ë ®©y giê nµy",

	"§Õn khuya råi vÉn cßn ®Õm sao",

	"H«m nay vÒ sím cóng mïng 1",

	"Míi bŞ vî chöi",

	"BŞ th»ng kia lõa hÕt 1kv",

	"Bang tuyÓn mem c«ng thµnh",

	"¤ cª con dª",

	"MÌ nheo vl",

	"Chóc b¹n may m¾n lÇn sau",

	"Em muèn c¾t ®«i nçi sÇu",

	"Ng­êi Êy yªu t«i chØ v× tiÒn",

	"ChØ cã c¸i miÖng lµ giái",

	"B¸n ®å D· TÈu, quÑo lùaaaaa",

	"Mua vò khİ LSNC gi¸ cao",

	"§­êng nµo ®i Kháa Lang §éng?",

	"Míi qu¸nh rít bİ kİp NMK nÌ!",

	"MÑ c¸i con C«n L«n Bïa",

	"Mua bæng BS >30, ai cã pm!",

	"Mai l¹i ph¶i ®i lµm, mÖt ghª",

	"Nhí bå cò qu¸",

	"Råi mµi sÏ gÆp qu¶ b¸o th«i con ¹",

	"LiÒu ¨n nhiÒu",

	"ChiÒu nay ch¾c lµm con l«",

	"TuyÓn Nga Mi VIP ®i v­ît ¶i, team ngon!",

	"Cßn 1 slot s¨n boss s¸t thñ",

	"Xin 1 slot s¨n boss s¸t thñ",

	"Mua ®ao cÊp 10, hÖ kim HNL",

	"Mua KNB ®©y",

	"VÒ T­¬ng D­¬ng coi mua l©n ®i",

	"Tau ®ang qua Tr­êng B¹ch l­îm ve chai",

	"Míi n»m m¬ thÊy rít ®­îc c¸i nhÉn V« Danh",

	"Trêi l¹nh ghª!",

	"Mai ch¾c nghØ ë nhµ",

	"S¾p bÖnh råi",

	"Th«i ®i vÒ ngñ",

	"Ta l¹c tr«i gi÷a trêi",

	"§«ng sang anh nhí em",

	"Kh«ng say kh«ng d×a",

	"Say ®Õn ®iªn d¹i, say hÕt kiÕp ng­êi",

	"Th¸ng n¨m th¨ng trÇm, dßng ®êi ng¶ nghiªng",

	"M×nh ch¼ng cïng víi nhau, ®i hÕt qu·ng ®­êng",

	"Ngµy x­a t«i còng yªu ng­êi t«i yªu ®Ñp xinh",

	"T¹i sao giê chóng ta l¹i l×a ®«i",

	"Lµ do ai v« t©m?",

	"§· rÊt l©u kh«ng cã ai bªn c¹nh",

	"Muèn ®­îc ai ®ã «m",

	"Ngµy x­a Êy ®«i ta bªn nhau kh«ng rêi",

	"Ta muèn lµm Vâ L©m Minh Chñ",

	"§õng khãc, ®õng buån nha em",

	"Tµn ®ªm nay lµ m×nh chia tay",

	"T×nh ®«i ta h«m nao, bao thiÕt tha mÆn nång",

	"Ch­a yªu lÇn nµo biÕt ra lµm sao",

	"Lì yªu ng­êi ta gieo tr¸i ngang",

	"Bao n¨m qua råi cßn gèi chiÕc",

	"Em sÏ lµ ng­êi ra ®i",

	"H«m nay cã m­a, m­a r¬i rÊt nhiÒu",

	"Mong ¸nh sao trêi kia ngõng m·i n¬i ®©y",

	"Cho xin 2 v¹n anh ¬i",

	"Míi bŞ trém ghĞ nhµ",

	"Míi bŞ ba qu¸nh",

	"Gia tr­ëng míi lo ®­îc cho em",

	"Kh¸t n­íc ghª",

	"Cã c«ng mµi s¾t cã ngµy nªn kim",

	"§­êng m«n qu¸nh kinh vl",

	"L­¬ng t©m c¾n røt qu¸",

	"CÇn vay tiÒn",

	"Em nghÌo qu¸, huhu",

	"huhuhu",

	"Kh«ng thÓ chÊp nhËn sù thËt nµy",

	"ThÊy tËn m¾t, b¾t tËn tay",

	"hahaha",

	"CÇn t×m ®Ö tö",

	"Nghe nãi muån lËp bang ph¶i cã Nh¹c V­¬ng KiÕm",

	"35 tuæi mµ cßn Õ nÌ",

	"Buån lµm chi lÖ hoen bê mi",

	"TiÒn l­¬ng kh«ng ®ñ tr¶ tiÒn nhµ. hic",

	"Xin lçi. Con bÊt hiÕu",

	"Coi chõng bŞ c¾n lĞn",

	"QuÇn Èu míi lµ v­¬ng ®¹o",

	"So¸i hay kh«ng so¸i?",

	"§õng solo gièng nh­ Vâ Dang KiÕm, nÕu kh«ng tù tin",

	"Coi chõng bŞ hÊp",

	"C« ®¬n gi÷a chèn ao hå",

	"MĞo hiÓu g× c¶",

	"LuyÖn skill l©u v·i lä",

	"CÇn mua Tiªn Th¶o Lé",

	"CÇn b¸n QuÕ Hoa Töu",

	"B¸n Lôc Thñy Tinh ®©y",

	"B¸n 5 Tinh Hå B¶o Th¹ch, xin c¸i gi¸",

	"500 anh em ®Õn D­¬ng Ch©u xem ®¸nh nhau nÌ",

	"Shop ®å max Kh¸ng më t¹i HiÖu Thuèc Thµnh §«",

	"H«m nay ®Ñp trêi, thİch hîp ®Ó nãi chia tay",

	"Ai b¸n phóc Duyªn kh«ng?",

	"Ğp c©y vò khİ bŞ xŞt mÊt tiªu",

	"Nh×n mÆt ta thÊy cã tiÒn h¶?",

	"HÑn gÆp l¹i",

	"Ch¹y lÑ",

	"TrÔ giê råi",

	"§ang c¶m thÊy kh«ng ®­îc kháe",

	"Cã c¸i mïi g× ®ã lµ l¹, ngé ngé",

	"H¾c x× h¬i",

	"TiÒn ®©u mµ mua g¹o ®©y",

	"ån µo qu¸",

	"Oan uèng qu¸, bao §¹i Nh©n",

	"Cãc ghÎ mµ ®ßi ¨n thŞt thiªn nga",

	"30 n¨m hµ ®«ng, 30 n¨m hµ t©y",

	"Ng­êi ta sinh ra ë v¹ch ®İch",

	"§­êng vµo tim sao b¨ng gi¸",

	"Xin ®õng yªu t«i",

	"Cã chuyÖn g× th× tõ tõ nãi, b×nh tÜnh",

	"Yªu hay kh«ng yªu?",

	"Hay lµ m×nh cø bÊt chÊp yªu nhau ®i",

	"B¾t con kiÕn bá trong quÇn",
	"TiÓu ®Ö ®Ö cña ta thËt hïng tr¸ng a",
	"§o xem cña ai to h¬n kh«ng",
	"M×nh thËt ngèc nghÕch",
	"Sau c¬n m­a lµ cÇu vßng",
	"Sù thËt mÊt lßng th«i",
	"Ng­êi yªu míi c¾m sõng tao",
	"Th«i ®õng buån n÷a mµ",
	"Buån lµm chi em ¬i",
	"Giê tİ canh ba, cÇn thËn cñi löa",
	"§óng lµ tiÒn nµo cña ®ã mµ",
	"¡n ph¶i ®å ¨n cò... bŞ tróng thùc",
	"Nghe nãi, cã thÇn thiÕt sÏ ®óc ®­îc thÇn binh",
	"Ta ®Õn tõ ThÇn Binh S¬n Trang",
	"N¬i ®©y thËt ®Ñp",
	"Yªn b×nh qu¸",
	"ThËt lµ an nhiªn",
	"C¶m thÊy dÔ chŞu",
	"Tíi giê ®ãn con råi",
	"BiÖn kinh cã biÕn",
	"Thµnh §« thËt giµu cã",
	"Ai mµ ch¼ng muèn cuéc sèng giµu sang",
	"Mét ngµy lµ huynh ®Ö, mét ®êi lµ huynh ®Ö",
	"T¹m biÖt, ta sÏ bÕ quan 10 n¨m",
	"Ng­êi l¹ ¬i, cho t«i m­în bê vai",
	"MÖt qu¸ ®ª",
	"Cø thÕ mµ triÓn",
	"B¸n nghÖ kh«ng b¸n th©n",
	"B¸n th©n kh«ng b¸n nghÖ",
	"§õng xa em ®ªm nay",
	"ThÕ gian nµy nguy hiÓm nhÊt lµ lßng ng­êi",
	"Bang m×nh nhÊt ®Şnh cã néi gi¸n",
	"§ªm nay ngñ ë ®©u?",
	"C« c«, ta yªu ng­¬i",
	"Kh«ng bù nh­ng mµ móp",
	"Cã thÓ gi¶m cho ta chót İt?",
	"Ng­¬i cã l­¬ng t©m kh«ng?",
	"Cuéc ®êi lªn voi xuèng chã",
	"Ta hËn thiªn",
	"Anh kh¹c hay em kh¹c",
	"ThËt chãi chang",
	"Sau c¬n m­a trêi l¹i s¸ng",
	"Mua 2 tÆng 1 ®©y",
	"Tan chî cmnr",
	"ChiÕc dĞp rít ®©u mÊt tiªu råi",
	"Ng­êi yªu yÕu sinh lİ qu¸",
	"C¸c h¹ cho ta hái th¨m...",
	"ZÌ zĞ ze",
	"ó lµ la",
	"ChuyÖn nµy tÊt cã mê ¸m",
	"Cã viÖc g× cho ta lµm kh«ng?",
	"ThiÕu thiÕu c¸i g× ®ã",
	"Cã m¸u cã thŞt, v× sao v« t×nh",
	"ThËt lµ thÊm thİa",
	"Khãc kh«ng thµnh tiÕng",
	"ViÖc vui kh«ng chØ cã mét",
	"L¹i 10 n¨m tr«i qua",
	"GiËn råi!",
	"Tau thİch mi",
	"§ang mÖt nha, ®õng cã chäc",
	"Tiªn tö, xin tù träng",
	"Con ®­êng t­¬ng lai thËt t­¬i s¸ng",
	"Ng­¬i cã lßng tù träng sao?",
	"Ca, ta nhí ng­¬i",
	"ThÌm chua qu¸ trêi",
	"Ai ®¸nh em ta?",
	"3 ngµy råi ch­a t¾m, thói qu¾c lu«n",
	"C¶ ngµy ch­a ®­îc ¨n g×",
	"Míi bŞ giËt hôi",
	"Huynh ®Ö, cho ta chót mÆt mòi",
	"ChuyÖn l¹ cã thËt",
	"G¹o nÊu thµnh c¬m mÊt råi",
	"Cßn kh«ng trÔ",
	"Lµm sao ®Ó t×m ®­îc nµng?",
	"H¾t x× h¬iiii",
	"§øng im, ®õng nhóc nhİch",
	"Ca nµy khã!",
	"Cã sao th× sèng vËy",
	"Nhµ giµu mµ keo kiÖt",
	"ThËt h©m mé Do·n Chİ B×nh",
	"Ta muèn ®i ngñ",
	"Cê b¹c lµ b¸c th»ng bÇn",
	"BÇn cïng sinh ®¹o tÆc a",
	"BiÕt vËy ta gia nhËp Vâ §ang",
	"BiÕt vËy ta gia nhËp Thóy Yªn",
	"BiÕt vËy ta gia nhËp Nga Mi",
	"BiÕt vËy ta gia nhËp ThiÕu L©m",
	"BiÕt vËy ta gia nhËp Thiªn V­¬ng Bang",
	"BiÕt vËy ta gia nhËp Ngò §éc Gi¸o",
	"BiÕt vËy ta gia nhËp §­êng M«n",
	"BiÕt vËy ta gia nhËp C¸i Bang",
	"BiÕt vËy ta gia nhËp Thiªn NhÉn Gi¸o",
	"BiÕt vËy ta gia nhËp C«n L«n Ph¸i",
	"BiÕt vËy ta gia nhËp Hoa S¬n",
	"BiÕt vËy ta gia nhËp Vò Hån",
	"BiÕt vËy ta gia nhËp Tiªu Dao",
	"C¸i Bang thiªn h¹ v« ®Şch thñ",
	"ThiÕu L©m thiªn h¹ v« ®Şch thñ",
	"Thiªn V­¬ng Bang thiªn h¹ v« ®Şch thñ",
	"Ngò §éc Gi¸o thiªn h¹ v« ®Şch thñ",
	"§­êng M«n thiªn h¹ v« ®Şch thñ",
	"Thiªn NhÉn thiªn h¹ v« ®Şch thñ",
	"Nga Mi thiªn h¹ v« ®Şch thñ",
	"Vâ §ang thiªn h¹ v« ®Şch thñ",
	"C«n L«n thiªn h¹ v« ®Şch thñ",
	"Tiªu Dao thiªn h¹ v« ®Şch thñ",
	"Vò Hån thiªn h¹ v« ®Şch thñ",
	"Hoa S¬n thiªn h¹ v« ®Şch thñ",
	"Nghe nãi, ngµy mai cã Hoa S¬n luËn kiÕm",
	"ThÌm M× VŞt TiÒm qu¸",
	"ThÌm Hñ TiÕu qu¸",
	"ThÌm Phë qu¸",
	"ThÌm Heo Quay qu¸",
	"ThÌm Cua qu¸",
	"ThÌm g¸i qu¸",
	"ThÌm SÇu Riªng ghª",
	"Muèn ¨n xiªn que",
	"Muèn ¨n thŞt n­íng",
	"R¨ng s©u mÊt råi",
	"§ang bŞ viªm häng",
	"ThÌm gµ n­íng qu¸",
	"L©u råi ch­a ®i nhËu",
	"Tèi nay cã r·nh kh«ng",
	"§Şnh tèi nay ®i ¨n trém",
	"Lµm nh­ vËy ®ñ råi",
	"Vâ c«ng d¹o nµy tiÕn bé chËm qu¸",
	"10 n¨m rÌn s¸ch l¹i thi rít",
	"Tuét hÕt c¶ høng",
	"§Ó vî lªn ®Çu chÕt a",
	"§Ó vî lªn ®Çu tr­êng sinh bÊt tö nha",
	"D¹o nµy kh«ng cã ®i lµm",
	"Cha ta d¹o nµy vÉn kháe",
	"MÑ ta vÉn tèt",
	"Nµo r¶nh ghĞ nhµ ta ch¬i",
	"Tû cña ta ngµy cµng xinh ®Ñp",
	"§i bé mái ch©n thËt",
	"VËt gi¸ ngµy cµng leo thang",
	"L­¬ng cµng ngµy cang İt",
	"Kinh tÕ thËt khã kh¨n",
	"Ng­¬i vÉn æn ®ã chø",
	"§¹i s­ tû, ng­¬i ë ®©u",
	"S­ phô tha thø cho ng­¬i",
	"§Ö ®Ö, ®i thanh l©u kh«ng?",
	"1 ®ªm, 2 xŞ",
	"D­îng ta ngo¹i t×nh, d× ta ®ang khãc",
	"Vî ta ®ang cã thai",
	"T×m kh¾p thiªn h¹ kh«ng thÊy Hîp Hoan T¸n",
	"Hoa S¬n TuyÕt Liªn l¹i xuÊt hiÖn",
	"Hoµng Kim Qu¶ ë t¹i nói Tr­êng B¹ch",
	"§µo Hoa Nguyªn xuÊt hiÖn cao thñ",
	"YÕn Tö §éng xuÊt hiÖn cao thñ",
	"KiÕm C¸c Thôc §¹o xuÊt hiÖn cao thñ",
	"C¸i Bang xuÊt hiÖn cao thñ",
	"Nga Mi xuÊt hiÖn cao thñ",
	"ThiÕu L©m xuÊt hiÖn cao thñ",
	"Thiªn V­¬ng xuÊt hiÖn cao thñ",
	"Ngò §éc xuÊt hiÖn cao thñ",
	"§­êng M«n xuÊt hiÖn cao thñ",
	"Thóy Yªn xuÊt hiÖn cao thñ",
	"Thiªn NhÉn xuÊt hiÖn cao thñ",
	"C«n L«n xuÊt hiÖn cao thñ",
	"Vò Hån xuÊt hiÖn cao thñ",
	"Tiªu Dao xuÊt hiÖn cao thñ",
	"Hoa S¬n xuÊt hiÖn cao thñ",
	"Ngùa quı t×m thÊy t¹i Ba L¨ng HuyÖn",
	"Ngùa quı t×m thÊy t¹i Long TuyÒn Th«n",
	"Ngùa quı t×m thÊy t¹i Giang T©n Th«n ",
	"Ngùa quı t×m thÊy t¹i VÜnh L¹c Th«n",
	"Ngùa quı t×m thÊy t¹i Long M«n TrÊn",
	"Ngùa quı t×m thÊy t¹i Chu Tiªn TrÊn",
	"Cã ®¸nh nhau lín t¹i BiÖn Kinh",
	"Cã ®¸nh nhau lín t¹i Thµnh §«",
	"Cã ®¸nh nhau lín t¹i D­¬ng Ch©u",
	"Cã ®¸nh nhau lín t¹i §¹i Lı",
	"Cã ®¸nh nhau lín t¹i Ph­îng T­êng",
	"Cã ®¸nh nhau lín t¹i L©m An",
	"Cã ®¸nh nhau lín t¹i T­¬ng D­¬ng",
	"ChØ lµ tiÓu ®¶ tiÓu nh¸o",
	"Thu mua HuyÒn ThiÕt!",
	"Thu mua Tinh Hång B¶o Th¹ch!",
	"Thu mua Thñy Tinh C¸c Lo¹i!",
	"Thu mua Bİ Kİp c¸c ph¸i!",
	"Thu mua HuyÒn Tinh!",
	"Thu mua Tµng B¶o §å!",
	"Thu mua Vò Khİ Hót Hİt!",
	"Thu mua Giµy TDDC!",
	"Thu mua Ngùa Quı!",
	"Thu mua ®å PTVL!",
	"Thu mua ®an d­îc!",
	"Thu mua ®å Hoµng Kim C¸c Ph¸i!",
	"B¸n HuyÒn ThiÕt, ai quan t©m ®Õn xem!",
	"B¸n Tinh Hång B¶o Th¹ch, ai quan t©m ®Õn xem!",
	"B¸n Thñy Tinh C¸c Lo¹i, ai quan t©m ®Õn xem!",
	"B¸n Bİ Kİp c¸c ph¸i, ai quan t©m ®Õn xem!",
	"B¸n HuyÒn Tinh, ai quan t©m ®Õn xem!",
	"B¸n Tµng B¶o §å, ai quan t©m ®Õn xem!",
	"B¸n Vò Khİ Hót Hİt, ai quan t©m ®Õn xem!",
	"B¸n Giµy TDDC, ai quan t©m ®Õn xem!",
	"B¸n Ngùa Quı, ai quan t©m ®Õn xem!",
	"B¸n ®å PTVL, ai quan t©m ®Õn xem!",
	"B¸n ®an d­îc, ai quan t©m ®Õn xem!",
	"B¸n ®å Hoµng Kim C¸c Ph¸i, ai quan t©m ®Õn xem!",
	"Ng­¬i thËt giµu cã",
	"C¸i ta thiÕu nhÊt lµ thêi gian",
	"§õng ®ïa n÷a",
	"H¶o huynh ®Ö",
	"Kh«ng say kh«ng vÒ",
	"ChØ lo ch¬i, kh«ng lo lµm ¨n",
	"Ng­¬i thËt l­êi biÕng",
	"Suèt ngµy ®Ö ta chØ lo ¨n ch¬i",
	"Giµ råi mµ kh«ng nªn nÕt",
	"Bí ng­êi ta, ¨n v¹",
	"Sao ng­¬i ®ông ta",
	"C« n­¬ng, ta muèn trªn ng­¬i",
	"§õng gië giäng l­u manh",
	"Thiªn h¹ nµy kh«ng cßn chç dung ta",
	"Cã thÓ lµ do ta mÖt mái",
	"Sèng tİch cùc lªn míi ®­îc",
	"MiÖt mµi quay tay, vËn may sÏ ®Õn",
	"Kh«ng tåi... kh«ng tåi",
	"M×nh thËt may m¾n",
	"Ta sÏ h¶o h¶o chiÕu cè ®Ö",
	"Ta chØ cã 1 ng­êi s­ tû",
	"MÉu th©n, ta m­ín lËp gia ®×nh a",
	"§i t×m c¸i nµng d©u",
	"Ta tù hµo vÒ gia ®×nh cña m×nh",
	"Sèng ph¶i biÕt tiÕt kiÖm",
	"C¸i g× kh«ng cÇn th× ®õng mua",
	"Huynh ®Ó tèt, ®õng ®Ó mÊt ®i",
	"Nghe nãi thÇn tiªn lµ cã thËt",
	"Ta muèn tu tiªn",
	"Ta muèn m¹nh h¬n",
	"Tiªu cùc... ®ã kh«ng ph¶i lµ c¸ch cña ta",
	"Hång trÇn mu«n mµu a",
	"Bµn tay cña ng­¬i thËt l¹nh",
	"H«m nay HiÖu Thuèc nghØ",
	"H«m nay TiÖm T¹p Hãa nghØ",
	"H«m nay Xa Phu nghØ",
	"H«m nay TiÒn Trang nghØ",
	"H«m nay D· TÈu nghØ",
	"H«m nay Vâ S­ nghØ",
	"H«m nay Tiªu S­ nghØ",
	"Nh­ vËy lµ qu¸ ®ñ råi",
	"H«m nay ta cïng ng­¬i tíi s¸ng",
	"Cµy hoµi mµ kh«ng xong",
	"Ng­¬i tu luyÖn ®Õn ®©u råi",
	"§i mua 3 c©n g¹o",
	"§i mua 1 miÕng thŞt ba chØ",
	"§i mua 2 con c¸",
	"§i mua 3 con gµ",
	"§i mua İt ®­êng",
	"§i mua b×nh r­îu",
	"R­îu N÷ Nhi Hång thËt th¬m",
	"Töu l©u BiÖn Kinh míi më",
	"Töu l©u D­¬ng Ch©u míi më",
	"Töu l©u T­¬ng D­¬ng míi më",
	"Töu l©u §¹i Lı míi më",
	"Töu l©u Thµnh §« míi më",
	"Töu l©u Ph­îng T­êng míi më",
	"Töu l©u L©m An míi më",
	"§õng v× mét chuyÖn kh«ng ®¸ng ®Ó nhí",
	"Mét khi ®· quyÕt, ®õng hèi hËn",
	"M¾t ta mê råi",
	"Míi ®©y ®· gÇn tèi råi sao",
	"Míi ®©y ®· gÇn s¸ng råi sao",
	"Mïa ®«ng ®· ®Õn",
	"Mïa h¹ ®· ®Õn",
	"Mïa thu ®· ®Õn",
	"Mïa xu©n ®· ®Õn",
	"§­êng phè thËt s¹ch sÏ",
	"N­íc s«i, tr¸nh ra",
	"CÊp b¸o, cÊp b¸o...",
	"Nhanh nhanh, tranh ®­êng",
	"Bµ mô nhanh lªn a",
	"Kh«ng thÓ lµm nh­ vËy ®­îc",
	"Ta vèn kh«ng ®Şnh lµm vËy",
	"Ta muèn mua ¸o míi",
	"Ta muèn mua ngùa míi",
	"Ta muèn mua nãn míi",
	"Ta muèn mua hé uyÓn míi",
	"Ta muèn mua ®ai l­ng míi",
	"Ta muèn mua vò khİ míi",
	"Ta muèn mua ngäc béi míi",
	"Ta muèn mua d©y chuyÒn míi",
	"Ta muèn mua phi phong míi",
	"Ta muèn mua Thæ §Şa Phï míi",
	"Ta thİch c¸i ¸o ®ã",
	"Ta thİch c¸i ngùa ®ã",
	"Ta thİch c¸i nãn ®ã",
	"Ta thİch c¸i hé uyÓn ®ã",
	"Ta thİch c¸i ®ai l­ng ®ã",
	"Ta thİch c¸i vò khİ ®ã",
	"Ta thİch c¸i ngäc béi ®ã",
	"Ta thİch c¸i d©y chuyÒn ®ã",
	"Ta thİch c¸i phi phong ®ã",
	"Ta thİch c¸i Thæ §Şa Phï ®ã",
	"Qu¸ tuyÖt vêi!",
	"M¸u nµy kh«ng ®ñ xµi",
	"TiÒn ®©u mµ ®Ó dµnh",
	"TiÒn ®©u mµ c­íi nµng ®©y",
	"TiÒn ®©u mµ mua ¸o míi",
	"TiÒn ®©u mµ mua ngùa míi",
	"TiÒn ®©u mµ mua nãn míi",
	"TiÒn ®©u mµ mua hé uyÓn míi",
	"TiÒn ®©u mµ mua ®ai l­ng míi",
	"TiÒn ®©u mµ mua vò khİ míi",
	"TiÒn ®©u mµ mua ngäc béi míi",
	"TiÒn ®©u mµ mua d©y chuyÒn míi",
	"TiÒn ®©u mµ mua phi phong míi",
	"TiÒn ®©u mµ mua Thæ §Şa Phï míi",
	"ThËt khã xö a",
	"Ng­¬i cã b¸n ¸o cña ng­¬i kh«ng?",
	"Ng­¬i cã b¸n ngùa cña ng­¬i kh«ng?",
	"Ng­¬i cã b¸n nãn cña ng­¬i kh«ng?",
	"Ng­¬i cã b¸n hé uyÓn cña ng­¬i kh«ng?",
	"Ng­¬i cã b¸n ®ai l­ng cña ng­¬i kh«ng?",
	"Ng­¬i cã b¸n vò khİ cña ng­¬i kh«ng?",
	"Ng­¬i cã b¸n ngäc béi cña ng­¬i kh«ng?",
	"Ng­¬i cã b¸n d©y chuyÒn cña ng­¬i kh«ng?",
	"Ng­¬i cã b¸n phi phong cña ng­¬i kh«ng?",
	"Ng­¬i cã b¸n Thæ §Şa Phï cña ng­¬i kh«ng?",
	"Nãi kh«ng chŞu nghØ lu«n",
	"Míi bŞ s­ phô ph¹t diÖn bİch",
	"Cöu chØ cÇm ma thËt lµ lîi h¹i",
	"ThiÕu L©m §ao thËt lµ lîi h¹i",
	"ThiÕu L©m QuyÒn thËt lµ lîi h¹i",
	"ThiÕu L©m Bæng thËt lµ lîi h¹i",
	"Thiªn V­¬ng Th­¬ng thËt lµ lîi h¹i",
	"Thiªn V­¬ng §ao thËt lµ lîi h¹i",
	"Thiªn V­¬ng Chïy thËt lµ lîi h¹i",
	"§­êng M«n BÉy thËt lµ lîi h¹i",
	"§­êng M«n Phi §ao thËt lµ lîi h¹i",
	"§­êng M«n Phi Tiªu thËt lµ lîi h¹i",
	"Ngò §éc Ch­ëng thËt lµ lîi h¹i",
	"Ngò §éc §ao thËt lµ lîi h¹i",
	"Thóy Yªn §ao thËt lµ lîi h¹i",
	"Thóy Yªn Song §ao thËt lµ lîi h¹i",
	"Thóy Yªn §ao thËt lµ lîi h¹i",
	"Nga Mi KiÕm thËt lµ lîi h¹i",
	"Nga Mi Ch­ëng thËt lµ lîi h¹i",
	"C¸i Bang Bæng thËt lµ lîi h¹i",
	"C¸i Bang Ch­ëng thËt lµ lîi h¹i",
	"Thiªn NhÉn §ao thËt lµ lîi h¹i",
	"Thiªn NhÉn Th­¬ng thËt lµ lîi h¹i",
	"Vâ §ang KiÕm thËt lµ lîi h¹i",
	"Vâ §ang Ch­ëng thËt lµ lîi h¹i",
	"C«n L«n Bïa thËt lµ lîi h¹i",
	"C«n L«n KiÕm thËt lµ lîi h¹i",
	"C«n L«n §ao thËt lµ lîi h¹i",
	"Vò Hån §ao thËt lµ lîi h¹i",
	"Vò Hån ThuÉn thËt lµ lîi h¹i",
	"Hoa S¬n KiÕm thËt lµ lîi h¹i",
	"Hoa S¬n Ch­ëng thËt lµ lîi h¹i",
	"Tiªu Dao KiÕm thËt lµ lîi h¹i",
	"Tiªu Dao CÇm thËt lµ lîi h¹i",
	"M¹c cao QuËt phong c¶nh h÷u t×nh a",
	"Hoa S¬n phong c¶nh h÷u t×nh a",
	"M¹n B¾c Th¶o Nguyªn phong c¶nh h÷u t×nh a",
	"§µo Hoa Nguyªn phong c¶nh h÷u t×nh a",
	"§¶o TÈy Tñy phong c¶nh h÷u t×nh a",
	"Háa Lang §éng phong c¶nh h÷u t×nh a",
	"TiÒn b¹c lµ vËt ngoµi th©n",
	"Trêi kh«ng phô lßng ng­êi",
	"ThØnh tho¶ng cÇn tÜnh t©m",
	"Kh«ng quan t©m",
	"MÆc kÖ tÊt c¶",
	"Ch¾c g¸c kiÕm tõ ®©y",
	"ThiÕu ı chİ chiÕn ®Êu",
	"Cuéc sèng thËt buån ch¸n",
	"Cø hay giËn hên vu v¬",
	"Kh«ng biÕt lµm thÕ nµo cho ®óng",
	"KÌo nhËu nhiÒu qu¸",
	"Kh«ng thİch l¾ng nghe",
	"Gi¶i quyÕt nh÷ng sai lÇm ®· x¶y ra",
	"C¶m ¬n mäi ng­êi rÊt nhiÒu",
	"Nguyªn nh©n chİnh lµ nh­ thÕ",
	"Muèn sôp ®æ",
	"§· kh«ng biÕt lÇn thø mÊy hái",
	"Nµng sím muén g× còng nghÜ ®Õn",
	"BÇu trêi h«m nay thËt nhiÒu sao",
	"Ng­¬i ®ang nh×n c¸i g×",
	"§¸ng tiÕc, ng­¬i kh«ng ph¶i ta",
	"Ch­a tíi giê më cöa",
	"Giã m¸t qu¸",
	"§i TiÓu Tróc L©m",
	"V« t×nh th­îng thiªn a",
	"Ng­¬i tíi ®©y lµm g×",
	"Ta sî ng­¬i l¹nh",
	"Ta kh«ng sî l¹nh",
	"N÷ ®Õ khãc, 2 m¾t ®Ém lÖ",
	"Tay h¾n thËt Êm ¸p",
	"Kh«ng ph¶i do ta nãi",
	"ThËt khã xö",
	"ThËt xÊu hæ",
	"§iÒm tØnh ®Õn kh«ng nãi g×",
	"T©m sÏ kh«ng ®æi",
	"CÇn 1 c¬ héi",
	"C¸i nµy ®ªm thËt dµi",
	"C¬m nµy thËt ngon a",
	"§ang m¬ mµng c¸i g× ®ã",
	"BÇu kh«ng khİ cã chót quû dŞ",
	"S¾c mÆt ®en tèi v« cïng",
	"Chíp ®«i m¾t ®Ñp",
	"Cã kh¶ n¨ng!",
	"Ng­¬i thËt lµ mét c¸i nh©n tµi a",
	"ChØ cßn 30 n¨m",
	"MÆt ta kh«ng İt nÕp nh¨n a",
	"Cµn kh«n muèn thay ®æi",
	"C¸i nµy ®©y lµ thÕ nµo",
	"§¹i khİ bµng b¹c",
	"Uy chÊn cöu thiªn",
	"NghÜ ®Õn mí ®Çu, kh«ng ngê ®Õn kÕt qu¶",
	"ThËt nghŞch thiªn cÊm kş",
	"Kh«ng ph¶i lµ ngÉu nhiªn",
	"§Õn tét cïng lµ thiÕu thø g×",
	"Lµm sao h¾n cã thÓ tİnh xa nh­ vËy",
	"HÕt th¶y ®· kh«ng träng yÕu",
	"Lu©n håi triÖt ®Ó ®o¹n tuyÖt",
	"1 ng­êi kh«ng lµm ®­îc",
	"H¾n chİnh lµ chñ ®éng, ta l¹i bŞ ®éng",
	"Tr¶ gi¸ chİnh lµ lo¹i nµo ®¹i giíi ®©u",
	"Ta muèn ®¸nh ph¸ cÊm kş",
	"Chí sî",
	"B©y giê míi biÕt c¸i g× gäi lµ hi väng",
	"§· kh«ng x¸c ®Şnh",
	"Tang th­¬ng kh«ng chŞu næi",
	"TiÒn bèi, ta cã tµi ®øc g×",
	"ThËt kh«ng d¸m tin t­ëng",
	"Ch¼ng qua lµ hi väng kĞo dµi",
	"§Ñp nh­ th¸i d­¬ng",
	"H¾n cuèi cïng ®· hãa diÖt",
	"DÇn dÇn ®i h­íng kÕt thóc",
	"Lµm sao cã thÓ",
	"§Òu ho¶ng sî",
	"Lµ cã bao nhiªu ®¸ng sî",
	"1 kh«ng ®ñ, liÒn 2",
	"§Òu kh«ng trän vÑn",
	"Giät n­íc m¾t ®Òu ch­a hong kh«",
	"Kh«ng biÕt ®ang hái ai",
	"Ch­a bao giê b×nh tÜnh nh­ vËy",
	"V× c¸i g× ta kh«ng thÓ lµm ®Õ",
	"B×nh tÜnh h¾n lµ ®¸ng sî nhÊt",
	"Lµm ng­êi run sî",
	"Cuèi cïng còng thµnh c«ng",
	"Khã tr¸ch a",
	"Xem xĞt mµ giËt m×nh",
	"Kh«ng cÇn nh­ vËy phiÒn to¸i",
	"V¹n chóng chó môc a",
	"Cµng giµ cµng m¹nh",
	"V¹n cæ kh«ng mét",
	"Qu¸ c­êng thŞnh",
	"¶o qu¸ ¶o",
	"VÊn ®Ò kh«ng lín",
	"Kh«ng cã chót nµo hoµi nghi",
	"H¾n chİnh lµ thÇn tho¹i sèng",
	"§Òu ë trªn ®­êng ®Õn",
	"T©m thÇn nãi nhãi",
	"Lªn nh­ diÒu gÆp giã",
	"Víi h¾n mµ nãi lµ c¬ duyªn t¹o hãa",
	"Coi th­êng chóng sinh a",
	"Cã trêi míi biÕt",
	"Lµ thËt kh«ng biÕt",
	"Ai còng ch­a thÊy qua",
	"Ch­a chõng cßn cã ¸c h¬n",
	"§Òu nh­ vËy däa ng­êi",
	"ThÇn s¾c còng ®Òu ho¶ng hèt",
	"Nh­ trong dù liÖu",
	"Qu¸ quen thuéc bãng l­ng",
	"Lu«n cã c¶m gi¸c kú qu¸i",
	"Bãng ng­êi kia thËt xinh ®Ñp",
	"Xem nh­ chÊp nhËn",
	"CÇn cã ı t­",
	"ThÕ nh©n ®Òu chê mong",
	"Mäi ng­êi ®Òu ®Õn",
	"ThÕ nh©n ¸nh m¾t ®Òu r¹ng rì",
	"C¸i nµy ®Òu cã chót méng bøc",
	"Cã chót bİ mËt",
	"Kh«ng cã t­ c¸ch ®Ó biÕt",
	"Kh«ng thÓ nghi ngê",
	"Tùa nh­ nh×n ra m¸nh khãe",
	"Nh­ thÕ nµo nh­ thÕ",
	"N­íc m¾t l­ng trßng",
	"Nªn minh b¹ch",
	"L¹i v« thÇn trİ",
	"§¹i biÓu th­îng thiªn ı chİ",
	"Thæn thøc th× thæn thøc",
	"Kh«ng thÕ nµo tù nhiªn ®­îc",
	"Tuæi thä ®ang c¹n dÇn",
	"Phong hoa tuyÖt ®¹i",
	"RÊt cã s¾c th¸i truyÒn k×",
	"ThËt thËt ®Ñp m¾t",
	"C¶m gi¸c cã phÇn kh«ng ch©n thËt",
	"ThËt thËt nÓ t×nh",
	"Lµ h¾n ta qu¸ kinh diÔm",
	"V« cïng n¸o nhiÖt",
	"Ai ®Õn ®Òu kh«ng tèt dïng",
	"Lµm lßng ng­êi run sî",
	"§i kia ®îi th«i",
	"§õng lµm rén, c¸i nµy ®ñ",
	"TuyÖt lÇn ®Çu tiªn nh×n thÊy",
	"ChØ v× h¾n qu¸ kinh diÔm",
	"Song quyÒn nan ®Şch tø thñ",
	"TriÖt ®Ó hçn lo¹n",
	"Muèn sôp ®æ",
	"Kh«ng biÕt cã nhiÒu İt ng­êi gÆp n¹n",
	"SÏ ch©n chİnh an æn",
	"Kh«ng thÊy kh«ng râ ai lµ ai",
	"1 ng­êi ®éc chiÕn tr¨m ng­êi",
	"QuÇn Èu cã quÇn Èu ®©u ph¸p",
	"§éc chiÕn cã ®éc chiÕn ®Êu ph¸p",
	"ThËt lµ cã bao nhiªu c­êng ®¹i",
	"Qu©n l©m thiªn h¹",
	"ThËt lóng tóng",
	"Sao ng­¬i l¹i hái ta",
	"Kh«ng biÕt ®· vÒ nhµ ch­a",
	"Thµnh thËt ®i",
	"H¸t cho ta nghe ®i",
	"MÆt ng­¬i dİnh g× k×a",
	"T©m ı ng­¬i, ta nhËn",
	"Mang vÒ nhµ dïng ®i",
	"T­ëng kh«ng yªu nh­ng yªu kh«ng t­ëng",
	"XÊu hæ th× xÊu hæ",
	"Cuèi cïng lµ ®Õn",
	"Nhu t×nh nh­ n­íc",
	"V¹n niÖm bªn trong cã vÜnh h»ng",
	"Toµn c¶nh lµ tang th­¬ng",
	"Tùu nhí râ",
	"Trong m¾t trµn ®Çy lÖ quang",
	"Cßn sÏ cã 1 trËn chiÕn",
	"§»ng sau cßn cã kiÕp sè",
	"§Ì nĞn thë kh«ng næi",
	"1 tiÕng nghÑn ngµo",
	"BŞ cho leo c©y råi",
	"Lêi nµy nãi rÊt cã tr×nh ®é",
	"Kh«ng ®ñ sè a",
	"C¸i nµy ®­îc nÌ",
	"§ang trªn ®­êng tíi",
	"Ta muèn ¨n kem",
	"Ta muèn ¨n xoµi",
	"Ta muèn ¨n d­a hÊu",
	"Ta muèn ¨n tµu hñ",
	"Ta muèn ¨n kÑo",
	"Ta muèn ¨n møt qu¶",
	"Ta muèn ¨n c¬m",
	"Ta kh¸t n­íc",
	"Ta thÌm ngät",
	"Ta muèn ¨n tr¸i c©y",
	"Ta muèn ¨n ng­¬i",
	"Ta muèn ¨n lÈu",
	"Ta muèn ¨n m×",
	"Ta muèn ¨n m× kh«",
	"Ta muèn ¨n d©u",
	"Ta muèn ¨n tr¸i ®µo",
	"Ta muèn ¨n chuèi",
	"Ta muèn ¨n ch©n gµ",
	"Ta muèn ¨n x«i",
	"Ta muèn ¨n hét vŞt lén",
	"Ta muèn ¨n kh« c¸",
	"Ta muèn ¨n hét gµ n­íng",
	"Ta muèn ¨n kh« mùc",
	"Ta muèn ¨n canh chua",
	"Ta muèn ¨n ®å n­íng",
	"Ta muèn ¨n c¸ chiªn",
	"Ta muèn ¨n rau luéc",
	"Ta muèn ¨n kim chi",
	"Ta muèn ¨n cµ ph¸o",
	"Ta muèn ¨n thŞt chã",
	"Ta muèn ¨n gµ ñ muèi",
	"Ta muèn ¨n gµ luéc",
	"Ta muèn ¨n vŞt quay",
	"Ta muèn ¨n gµ r¸n",
	"Ta muèn ¨n trøng chiªn",
	"Ta muèn ¨n t«m n­íng",
	"Ta muèn ¨n t«m luéc",
	"Ta muèn ¨n thŞt heo x«ng khãi",
	"Ta muèn ¨n thŞt tr©u g¸c bÕp",
	"Ta muèn ¨n mËt ong",
	"Ta muèn ¨n m¨ng côt",
	"Ta muèn ¨n ch«m ch«m",
	"Ta muèn ¨n trøng luéc",
	"Ta muèn ¨n b¸nh tr¸ng trén",
	"Ta muèn ¨n x«i mÆn",
	"Ta muèn ¨n c¬m nÕp",
	"Ta muèn ¨n b¾p luéc",
	"Ta muèn ¨n bón bß",
	"Ta muèn ¨n bón c¸",
	"Ta muèn ¨n nem n­íng",
	"Ta muèn ¨n c¬m s­ên",
	"Ta muèn ¨n b¸nh canh cua",
	"Ta muèn ¨n cua hÊp",
	"Ta muèn ¨n cua rang muèn",
	"Ta muèn ¨n mùc chiªn ­íc m¾m",
	"Ta muèn ¨n nghª hÊp x¶",
	"Ta muèn ¨n cua hoµng ®Õ",
	"Ta muèn ¨n èc len hÊp dõa",
	"Ta muèn ¨n èc b­u luéc",
	"Ta muèn ¨n èc g¹o",
	"Ta muèn ¨n lÈu bß",
	"Ta muèn ¨n ph¸ lÊu",
	"Ta muèn ¨n ruét kh×a",
	"Ta muèn ¨n thŞt kho tiªu",
	"Ta muèn ¨n canh c¶i tr¾ng",
	"Ta muèn ¨n b¸nh m× thŞt",
	"Ta muèn ¨n b¸nh m× xİu m¹i",
	"Ta muèn ¨n b¸nh m× èp la",
	"Ta muèn ¨n thŞt muèi chiªn",
	"Ta muèn ¨n c¸ kho tiªu",
	"Ta muèn ¨n Thiªn S¬n TuyÕt Liªn",
	"Ta muèn ¨n qu¶ Huy Hoµng",
	"Ta muèn ¨n rau xµo",
	"Ta muèn uèng n­íc",
	"Ta muèn uèng r­îu",
	"Ta muèn uèng n­íc Ğp",
	"Ta muèn uèng s÷a",
	"Ta muèn uèng trµ",
	"Ta muèn uèng s©m bæ l­îng",
	"Ta muèn uèng yÕn ch­ng",
	"Ta muèn uèng n­íc mİa",
	"Ta muèn uèng Tiªn Th¶o Lé",
	"Ta muèn uèng n­íc suèi",
	"Ta muèn uèng n­íc g¹o",
	"Ta muèn uèng n­íc canh",
	"Ta muèn uèng N÷ Nhi Hång",
	"Ta muèn uèng B¸ch Hoa Töu",
	"Ta muèn uèng Quúnh Hoa Ngäc Lé",
	"Ta muèn uèng n­íc tiÓu ®ång tö",
	"Ta muèn uèng n­íc ngät",
	"Ta muèn uèng n­íc chanh",
	"Ta muèn uèng n­íc l¹nh",
	"Ta muèn uèng n­íc nãng",
	"Ta muèn uèng cµ phª",
	"Ta muèn uèng cµ phª s÷a",
	"Ta muèn uèng b¹c xØu",
	"T¹m biÖt ng­êi yªu trong tiÒm thøc",
	"T¹m biÖt ng­êi yªu m×nh nhÊt",
	"NĞn cay ®¾ng!",
	"Ph¸t sÇu a",
	"Ch¾c ®i cöa sao",
	"§­êng ®­êng chİnh chİnh mµ lµm",
	"Lèi ®i cña riªng ta",
	"Xin ®õng lµm ta buån",
	"NÕu nh­...",
	"Lµm 1 lÇn, ¨n mét ®êi",
	"Lµm m·i ch¼ng giµu",
	"§éc th©n cã g× sai",
	"Xin 1 trµn vç tay",
	"§Õn ®©y ®i",
	"ThËt khã xö",
	"MÊy giê råi",
	"S¾p tèi råi",
	"S¾p s¸ng råi",
	"Cßn g× ®Ó nãi n÷a kh«ng",
	"Hái ®i c­ng",
	"H·y cho ta biÕt c¶m xóc cña ng­¬i",
	"Xui qu¸ xui",
	"Nãi cho râ rµng",
	"Nãi cho xong ®i",
	"Ng­¬i kh«ng ng¹i, ta ng¹i",
	"Th«i b©y giê nh­ vÇy",
	"Nh×n thËt say ®¾m",
	"VËy ®­îc kh«ng ta?",
	"Ng­¬i muèn hái g×?",
	"Bùc béi, bùc béi qu¸ µ",
	"§ang ®i mua g¹o",
	"§ang ®i mua thuèc",
	"§ang ®i mua thŞt heo",
	"§ang ®i mua thŞt bß",
	"Qu¸ nhiÒu ng­êi ®ang nh×n",
	"§ang ®i mua r­îu",
	"§ang ®i mua d­a hÊu",
	"§ang ®i mua rau",
	"ThËt ngoµi ı muèn",
	"§iÒu kh«ng ngo¹i lÖ",
	"§ang ®i mua thuèc",
	"§ang ®i mua ngùa",
	"Kh«ng giÕt chÕt h¾n míi lµ l¹",
	"Linh hån ®ang run rÈy",
	"Tr¸i víi ph¸p t¾c a",
	"§ang ®i mua ®å ¨n",
	"§ang ®i mua ®å nh¾m",
	"§ang ®i mua måi nhËu",
	"§ang ®i r­íc con ",
	"TiÕp xuèng ®¹i chiÕn sÏ v« cïng th¶m liÖt",
	"GiÆc ®· bŞ ®Èy lui",
	"D­¬ng Ch©u ®ang tuyÓn qu©n a",
	"BiÖn Kinh ®ang tuyÓn qu©n a",
	"§¹i Lı ®ang tuyÓn qu©n a",
	"T­¬ng D­¬ng ®ang tuyÓn qu©n a",
	"Ph­îng T­êng ®ang tuyÓn qu©n a",
	"Thµnh §« ®ang tuyÓn qu©n a",
	"L©m An ®ang tuyÓn qu©n a",
	"Khã lßng mµ phßng bŞ",
	"Ca, ®îi ta!",
	"Tû, ®îi ta!",
	"Muéi, ®îi ta!",
	"Cha, ®îi ta!",
	"N­¬ng, ®îi ta!",
	"S­ Phô, ®îi ta!",
	"Ch­ëng M«n, ®îi ta!",
	"Tr­ëng l·o, ®îi ta!",
	"S­ Huynh, ®îi ta!",
	"S­ Tû, ®îi ta!",
	"S­ Muéi, ®îi ta!",
	"Chóng ta lµ ®ång m«n!",
	"Phong L¨ng §é, ®· më",
	"M¹n B¾c Th¶o Nguyªn, ®· më",
	"No qu¸",
	"Kh«ng nhŞn ®­îc n÷a",
	"Vâ c«ng s¾p tiÕn giai",
	"Kh«ng träng yÕu n÷a råi",
	"Xem ®Òu hİt khİ l¹nh",
	"S¾c mÆt ®Òu ®en",
	"Kh«ng ph¶i trß ®ïa",
	"1 ®­êng truy, 1 ®­êng ®¸nh",
	"C¸i kia cßn ®¸nh cäng l«ng",
	"C¸i kia ®¸ng chÕt th­îng thiªn",
	"ThËt kh«ng dÔ dµng v­ît qua",
	"Nh©n sinh mu«n mµu a",
	"§Ñp m¾t a",
	"T©m ı cña ng­¬i, ta lÜnh",
	"Kh«ng ph¶i vËy, tÊt tæn thÊt",
	"D¹o nµy kh«ng nhµn rçi",
	"H«m nay kh«ng cã g× ®Ó lµm",
	"H«m nay nãng qu¸",
	"H«m nay l¹nh qu¸",
	"H«m nay Êm qu¸",
	"H«m nay m¸t qu¸ qu¸",
	"H«m nay kh« qu¸",
	"H«m nay m­a qu¸",
	"H«m nay giã qu¸",
	"H«m nay nhiÒu m©y qu¸",
	"§ã còng kh«ng ph¶i lµ xinh ®Ñp phong c¶nh",
	"ThËt lµ xinh ®Ñp phong c¶nh",
	"Thiªn thêi, ®Şa lîi, nh©n hßa",
	"H×nh t­îng ®Ñp m¾t",
	"§¹i khai, ®¹i hîp",
	"1 trËn t¹o hãa",
	"Cã cã ng­êi cã thÓ s¸nh vai",
	"Tïy ı x¸ch ra 1 c¸i ®Òu lµ chİ t«n",
	"Dï sao còng ph¶i cã thêi h¹n ®i",
	"RÊt lµ cãi m¾t",
	"Cã thÓ cïng ta sãng vai",
	"Kh«ng ng­êi cã thÓ ®­a ra ®¸p ¸n",
	"Thêi gian nh­ dõng l¹i",
	"Tù hµnh diÔn hãa chiªu thøc",
	"Kİch ®éng ®Òu muèn nh¶y lªn",
	"C­êi trµn ngËp nhu t×nh",
	"Cùc kú nµo nhiÖt",
	"Khong hÒ bËn t©m",
	"KiÒm chÕ a",
	"TruyÒn thuyÕt ®· thµnh thÇn tho¹i",
	"§Êt rung nói chuyÓn",
	"An t©m ®i",
	"VÉn lµ lÇn ®Çu gÆp",
	"CÇn ph¶i nãi râ",
	"Kh«ng nãi ®­îc, kh«ng t¶ ®­îc",
	"L·o bèi, tiÓu bèi ®Òu cã",
	"§ã chİnh lµ t¹o hãa",
	"Th¸nh ®Şa, còng kh«ng ph¶i lµ th¸nh ®Şa sao",
	"Mua vĞ vµo cöa",
	"Con hµng nµy kh«ng thµnh thËt",
	"Muèn ®i bé 1 chót",
	"§Õn tr¶ tiÒn",
	"1 lßng tu ®¹o",
	"Chİ c­êng ®Ønh phong còng ®Õn",
	"ChÆc l­ìi kh«ng th«i",
	"1 ngµy lÆng yªn mµ qua",
	"VÉn c¶m thÊy nhá bĞ",
	"Nh×n kh«ng thÊu",
	"Muèn nh×n lĞn",
	"Kh«ng thÓ tíi s¸nh vai",
	"MÆt 1 c¸i so 1 c¸i ®en",
	"TØnh kh«ng ®Õn",
	"Ngoµi nói kh«ng b×nh tÜnh",
	"Cã ng­êi 1 c©u ph¸ quan",
	"Kh«ng gian, thêi gian ®Òu dõng l¹i",
	"Kh«ng ng«n ng÷",
	"L·o §¹i!",
	"B×nh th­êng mét ngµy lÆng yªn mµ qua",
	"Trêi s¾p m­a råi",
	"Trêi s¾p n¾ng råi",
	"TuyÕt s¾p r¬i",
	"Mïa xu©n s¾p ®Õn",
	"Mïa h¹ s¾p ®Õn",
	"Mïa thu s¾p ®Õn",
	"Mïa ®«ng s¾p ®Õn",
	"Kh«ng ng­êi biÕt",
	"Tr­êng tån t¹i thÕ gian",
	"Nh­ mét giÊc méng",
	"T©m c¶nh kh«ng gièng nhau",
	"Theo mét ı nghÜa nµo ®ã",
	"Kh«ng nªn nãi lêi nµo",
	"Tèi nay chí ®i",
	"Kh«ng ngñ ®­îc",
	"Më miÖng ®Òu rÊt cã häc vÊn",
	"Qu¸ t­ëng niÖm",
	"Ng­¬i qu¸ lµ mét c¸i nh©n tµi",
	"Cuèi cïng lµ c¸ g× ®å ch¬i",
	"Thæi lªn tíi 9 tÇng m©y",
	"§Õn lÆng yªn, ®i lÆng yªn",
	"Ta cÊp bËc kh«ng ®ñ",
	"Ta cßn lµ c¸i kia",
	"Nhu hßa mµ «n nhu",
	"Gäi c¸i g× ®Òu kh«ng cã t©m bÖnh",
	"Nh©n qu¶ tuÇn hoµn",
	"Cùc kú béi phôc a",
	"Ta h«m nay hoµn toµn lµm ®­îc",
	"Kh«ng cÇn qu¸ l©u",
	"N¨m ®ã lµm kh«ng ®­îc, b©y giê cã thÓ",
	"Ngµy tèt c¶nh ®Ñp",
	"H×nh t­îng nªn v« cïng h­¬ng diÔm",
	"Tõ khi chia tay ®Õn giê kh«ng cã vÊn ®Ò g× chø",
	"Ng­¬i nhËn ra h¾n",
	"Ta vèn kh«ng biÕt",
	"ThËt khã t¸i t¹o",
	"Kh«ng thÓ gi¶i thİch",
	"§Õn tét cïng lµ c¸i g× ®Şa ph­¬ng",
	"Nã cÊt giÊu g× bİ mËt",
	"Kh«ng khái chÊn kinh a",
	"ThÕ giíi nµy thËt ®¸ng sî",
	"Qu¸ nhiÒu ®iÒu ch­a biÕt",
	"H¾n so ta may m¾n",
	"Con ®­êng kia...",
	"Cã thÕ 1 İt sù t×nh ®Òu kh«ng biÕt",
	"Cã thÓ nghÜ minh b¹ch",
	"ThËt khã t­ëng t­îng",
	"Së kiÕn l­îc ®ång",
	"§ång c¶m a",
	"H¼n lµ cßn cã",
	"Cßn t¹i trªn ®­êng lang thang",
	"Cã 1 lo¹i dù c¶m bÊt th­êng",
	"BiÕt İt cßn thªm İt",
	"Ng­¬i cho r»ng ta kh«ng muèn ®i",
	"§­êng nµo ®i",
	"Ai cã thÓ khai",
	"Ta cÇn thêi gian",
	"Cßn ph¶i chê...",
	"Cã rÊt nhiÒu ng­êi ®Õn b¸i pháng",
	"§«ng nh­ trÉy héi",
	"Kh«ng biÕt ®ang nh×n c¸i g×",
	"Dïng c­ìng Ğp xuyªn th¼ng qua",
	"§Òu mÑ nã kh«ng tíi",
	"§i ®­êng t­ thÕ cã phÇn ph¸ch lèi",
	"Cho ta mÊy phÇn mÆt mòi",
	"Lµ tæ ®éi tíi",
	"Còng ®Òu tíi",
	"T©m bçng nhiªn 1 trËn ®au",
	"TuÕ nguyÖt nh­ ®ao a",
	"Cã vÎ cµng thªm ®Ñp m¾t",
	"Muèn nh×n mét chót h­¬ng diÔm",
	"TiÓu nha ®Çu nµy ngµy cµng bÊt phµm",
	"Ng­¬i lµ ai trÎ con",
	"L¹i cùc kú bÊt phµm",
	"Ai cã thÓ so s¸nh ®­îc nµng",
	"Chİnh lµ phung phİ cña trêi",
	"Nãi chuyÖn rÊt cã th©m ı",
	"§ã lµ vİ dô rÊt tèt",
	"§Òu lµ kÎ kh«ng cßn nhiÒu tuæi thä",
	"Còng tuæi thä kh«ng nhiÔn",
	"Còng bÊt ®¾c dÜ",
	"Mãn nµy cã chót ®¾t",
	"Gi¶m gi¸ ®i",
	"§õng cã chĞm n÷a",
	"Khã cã thÓ nghŞch chuyÓn",
	"B¸n hµng cã l­¬ng t©m kh«ng",
	"B¸n m¾c qu¸ vËy",
	"Kh«ng kia lùc l­îng",
	"Ng­êi quan minh chİnh ®¹i",
	"Kh«ng nãi lêi mê ¸m",
	"C¸i nµy lµm sao cã ı tø?",
	"õng ùc, nuèt n­íc bät",
	"TiÒn kh«ng cã",
	"Kh«ng cã tiÒn",
	"Hót thuèc kh«ng?",
	"C¶m gi¸c võa vÆn rÊt tèt",
	"§å tèt!",
	"Lê mê cßn nhí râ",
	"§¸ng tiÕc, ®¹o h¹nh ta cßn ch­a ®ñ",
	"C­êi cã phÇn vui vÎ",
	"Cã bãng ng­êi!",
	"Cã thİch kh¸ch",
	"B¶o vÖ h¾n!",
	"B¶o vÖ ta!",
	"§uæi theo h¾n!",
	"Th«i bá ®i",
	"§o¹t thiªn t¹o hãa a",
	"ChËm r·i mµ ®i",
	"Kh«ng tiÔn",
	"S¾c trêi thËt u ¸m",
	"Cùc kú ch¾c ch¾n",
	"Cuéc ®êi thËt mong lung",
	"Nguyªn nh©n chİnh lµ nh­ thÕ",
	"Kh«ng cã ph¶n håi",
	"§İch thËt lµ nã",
	"Kh«ng ngoµi ı muèn",
	"ThËt cã quan hÖ",
	"1 b­íc lªn trêi",
	"BÊt h÷u truyªn thuyÕt a",
	"ViÖn binh ®ang ®Õn",
	"Suıt n÷a th× bŞ hñy nhµ",
	"Kh«ng nh×n thÊy lµ ai",
	"ThÊy kh«ng râ ch©n dung",
	"Ng­êi xuÊt thñ kia cã bao nhiªu c­êng ®¹i",
	"Nguyªn nh©n chİnh lµ nh×n ra",
	"Khã tr¸ch a",
	"Kh«ng thÓ vÜnh cöu tr­êng tån",
	"HËu sinh kh¶ quı a!",
	"Hoµn toµn chİnh x¸c cã biÕn cè",
	"Tùa nh­ ta n¨m ®ã",
	"Suy nghÜ bŞ ®¸nh g·y...",
	"Tªn kia... m¹ng ®ñ lín",
	"Thæn thøc kh«ng th«i",
	"Ta bá lì rÊt nhiÒu chuyÖn ®Æc s¾c",
	"So víi t­ëng t­îng, nghiªm träng h¬n",
	"H¬n ph©n n÷a lµ kh«ng t¹i",
	"Kh«ng nªn ®Õn",
	"Kh«ng cßn cã kh¶ n¨ng cßn sèng",
	"RÊt khã lµm ®­îc",
	"§Òu chó ®Şnh kh«ng thÓ quay vÒ",
	"Ph¶i nh¾m chuÈn míi ®­îc",
	"RÊt tiÕc vËn khİ kh«ng tèt",
	"VËn khİ rÊt cÇn thiÕt",
	"§· bÆc v« ©m tİn",
	"PhÇn lín ®· bŞ diÖt",
	"Cã thÓ nãi nh­ vËy",
	"§· tiªu hao hÇu nh­ kh«ng cßn",
	"TiÒn bèi, tr­íc nghØ ng¬i ®i",
	"Ph¶n Thanh - Phôc Minh",
	"H¾n kh«ng cã c¸i kia b¶n lÜnh",
	"Héi sÏ lóng tóng h¬n",
	"Cã thÓ bŞ diÖt",
	"Kh«ng thÊy cã bãng ng­êi",
	"§i lÇn nµy chİnh lµ d¨m ba th¸ng",
	"Cã s¸t khİ m·nh liÖt",
	"Cßn xem kh«ng râ l¾m",
	"BiÕn mÊt?",
	"Ai? Cót ra ®©y",
	"Ch¹y còng kh«ng chËm",
	"XuÊt thñ ng­êi thËt lµ ®¸ng sî",
	"Cã thÓ ta sÏ kh«ng nh×n lÇm",
	"Nh­ vËy, vÊn ®Ò tíi",
	"Cã phÇn lµ ªm tai",
	"Cïng ta, cïng nhau lªn ®­êng",
	"Trë vÒ t¹i chç!",
	"T­ c¸ch ®Òu lµ kh«ng cã",
	"Còng ph¶i thiÖt thßi",
	"Tôu v« cïng thª th¶m",
	"Kh«ng thÓ so",
	"Còng kh«ng tèt g×",
	"LiÒn lµ c¸i kú tİch",
	"Còng coi lµ mét c¸i lèi ®i",
	"§ã kh«ng ph¶i lµ hang chuét",
	"Chê ng­êi ra",
	"Bøc c¸ch kh«ng lµ b×nh th­êng cao",
	"ChÕt rÊt phiÒn muén",
	"§ã lµ c¸i ch©n lı",
	"Trë tay kh«ng kŞp!",
	"¤m c©y ®îi thá",
	"Tróng kÕ råi",
	"§iÖu hæ ly s¬n",
	"D­¬ng ®«ng kİch t©y",
	"§©u chØ chãi m¾t",
	"§· cã 3-5 ngµy",
	"G¸nh nÆng ®­êng xa",
	"L¹i rÊt tù gi¸c",
	"TuyÖt ®èi kh«ng ph¶i lµ b×nh th­êng",
	"Cã chót t­¬ng tù",
	"§Òu ®i ®©u råi",
	"TiÒn bèi, t×m c¸i g× ®©u",
	"Nh×n ®iÖu bé nµy...",
	"Ng­¬i, v× sao mµ c­êi?",
	"§îi ®­îc mét con c¸ lín",
	"Kh«ng ph¶i lµ hµng phæ th«ng",
	"Kinh ng¹c th× kinh ng¹c",
	"Ngµy mai ta trë l¹i",
	"Ta ®i lÊy thªm tiÒn",
	"Kh«ng cã ®ñ tiÒn mua",
	"Kh¸ch quan muèn thø g×",
	"Ta cã thÓ gióp g× ng­¬i?",
	"Cã thÓ mua cho ta mét c¸i b¸nh bao kh«ng?",
	"Cã thÓ mua cho ta mét İt thøc ¨n kh«ng?",
	"Cã thÓ mua cho ta mét b×nh r­îu kh«ng?",
	"G­¬ng mÆt kia d÷ tîn kh«ng chŞu nçi",
	"TiÕng nh¹c thËt hay",
	"ThÇn bİ mµ b¸ ®¹o",
	"ThÕ nµo l¹i cã c¸i nµy thao t¸c",
	"Khã lßng phßng bŞ",
	"T×m kh«ng ra",
	"Tªn kia tuyÖt ®èi lµ 1 c¸i Èn nÊp cao thñ",
	"Nh×n vÒ phİa tr­íc, 1 m¶nh h­ v«",
	"Phİa tr­íc m«ng lung 1 m¶nh",
	"H¬n ph©n n÷a, ®Òu ph¶i quú",
	"Kia cã bao nhiªu lîi h¹i a",
	"Ch¬i trèn t×m?",
	"Kh«ng d¸m ngoi ®Çu lªn",
	"ThËt kh«ng cßn c¸ch nµo kh¸c",
	"Tõ bá t×m kiÕm",
	"Cßn ch­a hiÓu thÊu ®¸o",
	"Ph­¬ng ph¸p nµy cµng trùc tiÕp",
	"Ng­êi kia ®· bÆc v« ©m tİn",
	"§i d¹o 1 vßng",
	"Khèng xÊu hæ ng­êi ®Òu chung chİ h­íng",
	"Xem nh­ bÕ quan",
	"Nµng lµ yªu nghiÖt",
	"H¾n ta cßn ¸p chÕ",
	"Mét ®­êng ®Òu t¹i ngé ®¹o",
	"Cßn v× n¨m ®ã sù t×nh mµ s¸m hèi",
	"Tªn rÊt hay",
	"Cã mét lo¹i c¶m gi¸c quen thuéc",
	"Cã thÓ chóng ta ch­a tõng gÆp mÆt",
	"TuyÖt ®èi lµ trÎ tuæi nhÊt cao thñ",
	"Ng­¬i c¸i nµy b¶n lÜnh kh«ng thÕ nµo tèt",
	"??i ca! Ta theo ng­¬i",
	"T? t?! Ta theo ng­¬i",
	"Cha! Ta theo ng­¬i",
	"N­¬ng! Ta theo ng­¬i",
	"Tû phu! Ta theo ng­¬i",
	"S­ ®Ö! Ta theo ng­¬i",
	"S­ mÉu! Ta theo ng­¬i",
	"Muéi! Ta theo ng­¬i",
	"S­ muéi! Ta theo ng­¬i",
	"Bang Chñ! Ta theo ng­¬i",
	"S­ huynh! Ta theo ng­¬i",
	"Huynh ®Ö! Ta theo ng­¬i",
	"B¸ b¸! Ta theo ng­¬i",
	"A Di! Ta theo ng­¬i",
	"Mong ®­îc mäi ng­êi gióp ®ì",
	"Chµo anh em, ai lµm nhiÖm vô chung kh«ng?",
	"Chµo bang héi, h«m nay mäi ng­êi thÕ nµo?",
	"NhiÖm vô nµy lµm sao ®Ó hoµn thµnh nhanh nhÊt?",
	"M×nh bŞ kÑt ë nhiÖm vô nµy, ai gióp víi",
	"Anh em tËp trung, chuÈn bŞ ®i s¨n boss",
	"CÇn thªm ng­êi ®Ó ®i phã b¶n",
	"Mäi ng­êi tËp trung ®Ó b¶o vÖ l·nh thæ",
	"Ai b¸n ®å nµy kh«ng? M×nh cÇn gÊp",
	"M×nh cã d­ ®å nµy, ai cÇn th× liªn hÖ",
	"§æi ®å, ai cã trang bŞ nµy th× m×nh muèn ®æi",
	"H«m nay ®«ng vui qu¸ mäi ng­êi nhØ",
	"Ai cã mÑo g× th× chia sÎ",
	"M×nh nghÜ nªn tËp trung n©ng kü n¨ng nµy tr­íc",
	"H«m nay cã kÕ ho¹ch g× kh«ng?",
	"CÇn ph©n chia nhiÖm vô râ rµng h¬n",
	"Mäi ng­êi tËp trung ë l·nh ®Şa bang nhĞ",
	"Ng­êi si nãi méng",
	"Cã viÖc quan träng, Bang Chñ nãi tËp trung",
	"Ph¶i cã ng­êi gi÷ cöa, ai t×nh nguyÖn?",
	"CÈn thËn, cã mai phôc!",
	"KÎ ®Şch ®ang ®Õn gÇn, chuÈn bŞ s½n sµng!",
	"M×nh bŞ kÑt ë ®©y, ai gióp m×nh víi",
	"Ta võa häc ®­îc chiªu míi, ai muèn thö kh«ng?",
	"Cã ai tham gia sù kiÖn nµy kh«ng?",
	"LËp nhãm ®i!",
	"Nªn tËp trung vµo kü n¨ng phßng thñ tr­íc",
	"Kinh nghiÖm cña ng­¬i thËt phong phó",
	"Ch¬i ph¸i nµy cÇn chó ı g×?",
	"Ai cã kinh nghiÖm chia sÎ víi",
	"Ai cã chuyÖn g× vui kÓ nghe ch¬i",
	"H«m nay cã g× míi kh«ng?",
	"Ai solo kh«ng?",
	"Th¸ch ®Êu 1vs1, ai tù tin th× b­íc lªn",
	"Ta ®Õn tõ bang héi kh¸c",
	"Muèn giao l­u kÕt b¹n",
	"Ta s½n sµng chia sÎ",
	"Ai cã thÓ b¶o vÖ ta kh«ng?",
	"BŞ b¾t cãc, cÇn cøu gióp",
	"Lµm sao ®Ó th¾ng ®©y?",
	"C¶m ¬n v× ®· gióp ®ì",
	"Ta sÏ nhí ¬n ng­¬i",
	"Ng­¬i rÊt giái",
	"H·y cè g¾ng",
	"Chóng ta sÏ v­ît qua thö th¸ch",
	"Ai còng cã thÓ lµm ®­îc",
	"H·y tin vµo b¶n th©n",
	"Håi hép  qu¸",
	"Håi hép ghª",
	"S¾p tíi l­ît ta råi",
	"Ng­¬i ®ang chê ®iÒu g×?",
	"C¶m gi¸c thËt th¨ng hoa",
	"A! Lªn cÊp råi",
	"Võa míi bŞ ®¸nh",
	"Mäi ng­êi cïng nhau chia vui",
	"Chia buån nha",
	"Ai cã thuèc håi m¸u kh«ng",
	"CÇn tËp trung vµo ®iÓm yÕu cña boss",
	"CÇn lµm chËm nã",
	"CÇn lµm cho¸ng nã",
	"CÇn ®èt nã",
	"Ta sÏ ®i dß ®­êng tr­íc",
	"Mäi ng­êi theo sau hç trî",
	"Ng­¬i b¶o vÖ, ta tÊn c«ng",
	"NhiÖm vô nµy khã qu¸",
	"CÇn gióp ®ì",
	"Chóng ta lµm tèt l¾m",
	"H·y chuÈn bŞ cho nhiÖm vô tiÕp theo",
	"KiÓm tra kü nhĞ",
	"KiÓm tra trang bŞ vµ ®an ®­îc tr­íc khi chiÕn ®Êu",
	"Chóng ta ®· th¾ng!",
	"Mäi ng­êi thËt tuyÖt vêi",
	"Sù kiÖn sÏ diÔn ra vµo tèi nay",
	"Th­ gi·n ®i",
	"Sù kiÖn sÏ cã phÇn th­ëng, ®õng bá lì",
	"§õng tõ bá",
	"Ta cÇn mua kiÕm cao cÊp",
	"Ta cÇn mua ®ao cao cÊp",
	"Ta cÇn mua Th­¬ng cao cÊp",
	"Ta cÇn mua C«n cao cÊp",
	"Ta cÇn mua ®µn cao cÊp",
	"Ta cÇn mua ¸o cao cÊp",
	"Ta cÇn mua hé uyÓn cao cÊp",
	"Ta cÇn mua ngäc béi cao cÊp",
	"Ta cÇn mua d©y chuyÒn cao cÊp",
	"Ta cÇn mua giµy cao cÊp",
	"Ta cÇn mua nhÉn cao cÊp",
	"Ta cÇn mua phi phong cao cÊp",
	"Ta cÇn mua ngùa cao cÊp",
	"Ai cã ®å thõa cho ta víi",
	"Ta cÇn t×m mét sè vËt phÈm nhiÖm vô",
	"Ai cã thÓ cho ta m­în İt vµng kh«ng",
	"Ta nªn lµm g×",
	"Cã g× ®Æc biÖt kh«ng?",
	"TrËn ®Êu rÊt gay cÊn",
	"Chóng ta ®ang dÉn ®Çu, mäi ng­êi cè lªn",
	"Chóng ta ®ang cã lîi thÕ",
	"Ai cßn ch­a nép tµi nguyªn bang héi?",
	"Ai cÇn hç trî vÒ trang bŞ th× nãi ta",
	"NÕu cÇn gióp ®ì g× th× cø hái nhĞ",
	"Chóng ta ®· chiÕm ®­îc cæng chİnh",
	"TiÕp tôc tiÕn lªn",
	"Ai biÕt chç nµo t×m ®­îc c¸i nµy kh«ng?",
	"Míi t×m ®­îc kho b¸u",
	"Ai ®i t×m kho b¸u chung kh«ng?",
	"Ai cÇn g×, ta cã thÓ chia sÎ",
	"TËp trung, ®õng ®Ó bŞ ph©n t¸n",
	"CÈn thËn cã c¹m bÉy",
	"Mäi ng­êi tËp hîp t¹i ®Êu tr­êng",
	"ChuÈn bŞ vµo trËn",
	"Ta sÏ tÊn c«ng tõ bªn tr¸i",
	"Mäi ng­êi theo s¸t nhĞ!",
	"Ai d¸m tham gia thö th¸ch cïng nhau kh«ng?",
	"Ngµy mai gÆp l¹i",
	"Ta ph¶i ®i råi, ë l¹i vui vÎ",
	"§õng buån khi thua ta",
	"TrËn nµy sÏ thó vŞ h¬n",
	"§Õn ®©y mµ thö søc",
	"TrËn chiÕn h¹ng nÆng, ai d¸m?",
	"Ta ®· häc hái rÊt nhiÒu tõ ng­¬i",
	"C¶m gi¸c thËt tuyÖt vêi",
	"Ta cÇn mua mét mãn ®å ®Æc biÖt",
	"Ai cã b¸n kh«ng?",
	"§æi ®å kh«ng?",
	"Cho ta tr¶ l¹i ®å",
	"Ta kh«ng thÓ hoµn thµnh nhiÖm vô",
	"CÇn ng­êi lµm chung nhiÖm vô",
	"Ai b¸n Tiªn Th¶o Lé kh«ng?",
	"Ai b¸n QuÕ Hoa Töu kh«ng?",
	"Ai b¸n N÷ Nhi Hång kh«ng?",
	"Ai b¸n Thiªn S¬n TuyÕt Liªn kh«ng?",
	"Ai b¸n Chïy HSL kh«ng?",
	"Ai b¸n §ao HNL kh«ng?",
	"Ai b¸n Th­¬ng HSL kh«ng?",
	"Ai b¸n KiÕm HNL kh«ng?",
	"Ai b¸n KiÕm HSL kh«ng?",
	"Ai b¸n vò khİ tèc ®é xuÊt chiªu kh«ng?",
	"Ai b¸n ngùa ChiÕu D¹ kh«ng?",
	"Gi¸ bİ kİp ThiÕu L©m §ao bao nhiªu vËy?",
	"Gi¸ bİ kİp ThiÕu L©m QuyÒn bao nhiªu vËy?",
	"Gi¸ bİ kİp ThiÕu L©m Bæng bao nhiªu vËy?",
	"Gi¸ bİ kİp Thiªn V­¬ng Th­¬ng bao nhiªu vËy?",
	"Gi¸ bİ kİp Thiªn V­¬ng Chïy bao nhiªu vËy?",
	"Gi¸ bİ kİp Thiªn V­¬ng §ao bao nhiªu vËy?",
	"Gi¸ bİ kİp Ngò §éc Ch­ëng bao nhiªu vËy?",
	"Gi¸ bİ kİp Ngò §éc §ao bao nhiªu vËy?",
	"Gi¸ bİ kİp Thóy Yªn Song §ao bao nhiªu vËy?",
	"Gi¸ bİ kİp Thóy Yªn §ao bao nhiªu vËy?",
	"Gi¸ bİ kİp §­êng M«n BÉy bao nhiªu vËy?",
	"Gi¸ bİ kİp §­êng M«n Phi Tiªu bao nhiªu vËy?",
	"Gi¸ bİ kİp §­êng M«n Phi §ao bao nhiªu vËy?",
	"Gi¸ bİ kİp C¸i Bang Bæng bao nhiªu vËy?",
	"Gi¸ bİ kİp C¸i Bang Ch­ëng bao nhiªu vËy?",
	"Gi¸ bİ kİp Thiªn NhÉn §ao bao nhiªu vËy?",
	"Gi¸ bİ kİp Thiªn NhÉn Th­¬ng bao nhiªu vËy?",
	"Gi¸ bİ kİp Vò Hån §ao bao nhiªu vËy?",
	"Gi¸ bİ kİp Vò Hån ThuÉn bao nhiªu vËy?",
	"Gi¸ bİ kİp Tiªu Dao KiÕm bao nhiªu vËy?",
	"Gi¸ bİ kİp Tiªu Dao Ch­ëng bao nhiªu vËy?",
	"Gi¸ bİ kİp Hoa S¬n KiÕm bao nhiªu vËy?",
	"Gi¸ bİ kİp Hoa S¬n Ch­ëng bao nhiªu vËy?",
	"Gi¸ nµy h¬i cao, cã thÓ gi¶m ®­îc kh«ng?",
	"§ao nµy cã thuéc tİnh g× ®Æc biÖt?",
	"KiÕm nµy cã thuéc tİnh g× ®Æc biÖt?",
	"Th­¬ng nµy cã thuéc tİnh g× ®Æc biÖt?",
	"Bæng nµy cã thuéc tİnh g× ®Æc biÖt?",
	"Phi ®ao nµy cã thuéc tİnh g× ®Æc biÖt?",
	"Phi tiªu nµy cã thuéc tİnh g× ®Æc biÖt?",
	"CÇm nµy cã thuéc tİnh g× ®Æc biÖt?",
	"ThuÉn nµy cã thuéc tİnh g× ®Æc biÖt?",
	"¸o nµy cã thuéc tİnh g× ®Æc biÖt?",
	"Ngùa nµy cã thuéc tİnh g× ®Æc biÖt?",
	"Phi Phong nµy cã thuéc tİnh g× ®Æc biÖt?",
	"Nãn nµy cã thuéc tİnh g× ®Æc biÖt?",
	"D©y chuyÒn nµy cã thuéc tİnh g× ®Æc biÖt?",
	"Hé UyÓn nµy cã thuéc tİnh g× ®Æc biÖt?",
	"NhÉn nµy cã thuéc tİnh g× ®Æc biÖt?",
	"Ngäc béi nµy cã thuéc tİnh g× ®Æc biÖt?",
	"Th¾t l­ng nµy cã thuéc tİnh g× ®Æc biÖt?",
	"Giµy nµy cã thuéc tİnh g× ®Æc biÖt?",
	"Vò khİ nµy cã thuéc tİnh g× ®Æc biÖt?",
	"§ao nµy ®· n©ng cÊp ch­a?",
	"KiÕm nµy ®· n©ng cÊp ch­a?",
	"Th­¬ng nµy ®· n©ng cÊp ch­a?",
	"Bæng nµy ®· n©ng cÊp ch­a?",
	"Phi ®ao nµy ®· n©ng cÊp ch­a?",
	"Phi tiªu nµy ®· n©ng cÊp ch­a?",
	"CÇm nµy ®· n©ng cÊp ch­a?",
	"ThuÉn nµy ®· n©ng cÊp ch­a?",
	"¸o nµy ®· n©ng cÊp ch­a?",
	"Ngùa nµy ®· n©ng cÊp ch­a?",
	"Phi Phong nµy ®· n©ng cÊp ch­a?",
	"Nãn nµy ®· n©ng cÊp ch­a?",
	"D©y chuyÒn nµy ®· n©ng cÊp ch­a?",
	"Hé UyÓn nµy ®· n©ng cÊp ch­a?",
	"NhÉn nµy ®· n©ng cÊp ch­a?",
	"Ngäc béi nµy ®· n©ng cÊp ch­a?",
	"Th¾t l­ng nµy ®· n©ng cÊp ch­a?",
	"Giµy nµy ®· n©ng cÊp ch­a?",
	"Vò khİ nµy ®· n©ng cÊp ch­a?",
	"§ång ı mua, chóng ta giao dŞch ë Thµnh §« nha",
	"§ång ı mua, chóng ta giao dŞch ë BiÖn Kinh nha",
	"§ång ı mua, chóng ta giao dŞch ë D­¬ng Ch©u nha",
	"§ång ı mua, chóng ta giao dŞch ë T­¬ng D­¬ng nha",
	"§ång ı mua, chóng ta giao dŞch ë §Şa Lı nha",
	"§ång ı mua, chóng ta giao dŞch ë Ph­îng T­êng nha",
	"§ång ı mua, chóng ta giao dŞch ë L©m An nha",
	"ChuyÓn tiÒn råi, kiÓm tra vµ göi ®å gióp m×nh",
	"Chóng ta gÆp nhau ë Thµnh §« nha",
	"Chóng ta gÆp nhau ë BiÖn Kinh nha",
	"Chóng ta gÆp nhau ëD­¬ng Ch©u nha",
	"Chóng ta gÆp nhau ë T­¬ng D­¬ng nha",
	"Chóng ta gÆp nhau ë §Şa Lı nha",
	"Chóng ta gÆp nhau ë Ph­îng T­êng nha",
	"Chóng ta gÆp nhau ë L©m An nha",
	"VËt phÈm nµy kiÕm ë ®©u vËy?",
	"§ao nµy kiÕm ë ®©u vËy?",
	"KiÕm nµy kiÕm ë ®©u vËy?",
	"Th­¬ng nµy kiÕm ë ®©u vËy?",
	"Bæng nµy kiÕm ë ®©u vËy?",
	"Phi ®ao nµy kiÕm ë ®©u vËy?",
	"Phi tiªu nµy kiÕm ë ®©u vËy?",
	"Bæng nµy kiÕm ë ®©u vËy?",
	"CÇm nµy kiÕm ë ®©u vËy?",
	"ThuÉn nµy kiÕm ë ®©u vËy?",
	"¸o nµy kiÕm ë ®©u vËy?",
	"Ngùa nµy kiÕm ë ®©u vËy?",
	"Phi Phong nµy kiÕm ë ®©u vËy?",
	"Nãn nµy kiÕm ë ®©u vËy?",
	"D©y chuyÒn kiÕm ë ®©u vËy?",
	"Hé UyÓn kiÕm ë ®©u vËy?",
	"NhÉn nµy kiÕm ë ®©u vËy?",
	"Ngäc béi nkiÕm ë ®©u vËy?",
	"Th¾t l­ng nµy kiÕm ë ®©u vËy?",
	"Giµy nµy kiÕm ë ®©u vËy?",
	"Vò khİ nµy kiÕm ë ®©u vËy?",
	"Cã ai lµm trung gian giao dŞch kh«ng?",
	"Ta cÇn mua 1 c©y vò khİ cÊp 10, ai b¸n kh«ng?",
	"Ta cÇn mua 1 c©y ®ao cÊp 10, ai b¸n kh«ng?",
	"Ta cÇn mua 1 c©y th­¬ng cÊp 10, ai b¸n kh«ng?",
	"Ta cÇn mua 1 c©y bæng cÊp 10, ai b¸n kh«ng?",
	"Ta cÇn mua 1 c©y phi ®ao cÊp 10, ai b¸n kh«ng?",
	"Ta cÇn mua 1 c©y phi tiªu cÊp 10, ai b¸n kh«ng?",
	"Ta cÇn mua 1 ¸o gi¸p cÊp 10, ai b¸n kh«ng?",
	"Ta cÇn mua 1 nãn cÊp 10, ai b¸n kh«ng?",
	"Ta cÇn mua 1 hé uyÓn cÊp 10, ai b¸n kh«ng?",
	"Ta cÇn mua 1 nhÉn cÊp 10, ai b¸n kh«ng?",
	"Ta cÇn mua 1 ngäc béi cÊp 10, ai b¸n kh«ng?",
	"Ta cÇn mua 1 ®ai l­ng cÊp 10, ai b¸n kh«ng?",
	"Ta cÇn mua 1 giµy cÊp 10, ai b¸n kh«ng?",
	"Ta cÇn mua 1 ngùa cÊp 10, ai b¸n kh«ng?",
	"Ta cÇn mua 1 phi phong cÊp 10, ai b¸n kh«ng?",
	"Ai b¸n thuèc håi m¸u lo¹i m¹nh kh«ng?",
	"Ai b¸n thuèc håi néi lùc lo¹i m¹nh kh«ng?",
	"Ai b¸n thuèc håi thÓ lùc lo¹i m¹nh kh«ng?",
	"Ai b¸n thuèc gi¶i ®éc lo¹i m¹nh kh«ng?",
	"§ang cã vµi Tinh Hång B¶o Th¹ch cÇn b¸n, ai mua?",
	"§ang cã vµi Tiªn Th¶o Lé cÇn b¸n, ai mua?",
	"§ang cã vµi Thñy Tinh cÇn b¸n, ai mua?",
	"§ang cã vµi Bİ Kİp Vâ C«ng cÇn b¸n, ai mua?",
	"§ang cã vµi ThiÕt La H¸n cÇn b¸n, ai mua?",
	"§ang cã vµi B¸t Nh· Kinh cÇn b¸n, ai mua?",
	"§ang cã vµi Tµng B¶o §å cÇn b¸n, ai mua?",
	"§ang cã vµi Vâ L©m MËt TŞch cÇn b¸n, ai mua?",
	"§ang cã vµi vò khİ xŞn cÇn b¸n, ai mua?",
	"§ang cã vµi nhÉn xŞn cÇn b¸n, ai mua?",
	"§ang cã vµi ¸o xŞn cÇn b¸n, ai mua?",
	"§ang cã vµi mò xŞn cÇn b¸n, ai mua?",
	"§ang cã vµi d©y chuyÒn xŞn cÇn b¸n, ai mua?",
	"§ang cã vµi hé uyÓn xŞn cÇn b¸n, ai mua?",
	"§ang cã vµi ngäc béi xŞn cÇn b¸n, ai mua?",
	"§ang cã vµi ®ai l­ng xŞn cÇn b¸n, ai mua?",
	"§ang cã vµi giµy cÇn b¸n, ai mua?",
	"§ang cã vµi ngùa xŞn cÇn b¸n, ai mua?",
	"§ang cã vµi phi phong xŞn cÇn b¸n, ai mua?",
	"Ta muèn mua bİ kİp nµy, nh­ng gi¸ h¬i cao",
	"Ta muèn mua tr©n b¶o nµy, nh­ng gi¸ h¬i cao",
	"Ta muèn mua b¹ch cÇu hoµn nµy, nh­ng gi¸ h¬i cao",
	"Ta muèn mua kiÕm nµy, nh­ng gi¸ h¬i cao",
	"Ta muèn mua ®ao nµy, nh­ng gi¸ h¬i cao",
	"Ta muèn mua th­¬ng nµy, nh­ng gi¸ h¬i cao",
	"Ta muèn mua bæng nµy, nh­ng gi¸ h¬i cao",
	"Ta muèn mua phi ®ao nµy, nh­ng gi¸ h¬i cao",
	"Ta muèn mua phi tiªu nµy, nh­ng gi¸ h¬i cao",
	"Ta muèn mua cÇm nµy, nh­ng gi¸ h¬i cao",
	"Ta muèn mua thuÉn nµy, nh­ng gi¸ h¬i cao",
	"Ta muèn mua ¸o nµy, nh­ng gi¸ h¬i cao",
	"Ta muèn mua mò nµy, nh­ng gi¸ h¬i cao",
	"Ta muèn mua d©y chuyÒn nµy, nh­ng gi¸ h¬i cao",
	"Ta muèn mua hé uyÓn nµy, nh­ng gi¸ h¬i cao",
	"Ta muèn mua nhÉn nµy, nh­ng gi¸ h¬i cao",
	"Ta muèn mua ngäc béi nµy, nh­ng gi¸ h¬i cao",
	"Ta muèn mua giµy nµy, nh­ng gi¸ h¬i cao",
	"Ta muèn mua ngùa nµy, nh­ng gi¸ h¬i cao",
	"Ta muèn mua phi phong nµy, nh­ng gi¸ h¬i cao",
	"Ta muèn mua thñy tinh nµy, nh­ng gi¸ h¬i cao",
	"Ta muèn mua tinh hång b¶o th¹ch nµy, nh­ng gi¸ h¬i cao",
	"Bİ kİp nµy, cã thÓ th­¬ng l­îng ®­îc kh«ng?",
	"Tr©n b¶o nµy, cã thÓ th­¬ng l­îng ®­îc kh«ng?",
	"B¹ch cÇu hoµn nµy, cã thÓ th­¬ng l­îng ®­îc kh«ng?",
	"KiÕm nµy, cã thÓ th­¬ng l­îng ®­îc kh«ng?",
	"§ao nµy, cã thÓ th­¬ng l­îng ®­îc kh«ng?",
	"Th­¬ng nµy, cã thÓ th­¬ng l­îng ®­îc kh«ng?",
	"Bæng nµy, cã thÓ th­¬ng l­îng ®­îc kh«ng?",
	"Phi ®ao nµy, cã thÓ th­¬ng l­îng ®­îc kh«ng?",
	"Phi tiªu nµy, cã thÓ th­¬ng l­îng ®­îc kh«ng?",
	"CÇm nµy, cã thÓ th­¬ng l­îng ®­îc kh«ng?",
	"ThuÉn nµy, cã thÓ th­¬ng l­îng ®­îc kh«ng?",
	"¸o nµy, cã thÓ th­¬ng l­îng ®­îc kh«ng?",
	"Mò nµy, cã thÓ th­¬ng l­îng ®­îc kh«ng?",
	"D©y chuyÒn nµy, cã thÓ th­¬ng l­îng ®­îc kh«ng?",
	"Hé uyÓn nµy, cã thÓ th­¬ng l­îng ®­îc kh«ng?",
	"NhÉn nµy, cã thÓ th­¬ng l­îng ®­îc kh«ng?",
	"Ngäc béi nµy, cã thÓ th­¬ng l­îng ®­îc kh«ng?",
	"Giµy nµy, cã thÓ th­¬ng l­îng ®­îc kh«ng?",
	"Ngùa nµy, cã thÓ th­¬ng l­îng ®­îc kh«ng?",
	"Phi phong nµy, cã thÓ th­¬ng l­îng ®­îc kh«ng?",
	"Thñy tinh nµy, cã thÓ th­¬ng l­îng ®­îc kh«ng?",
	"Tinh hång b¶o th¹ch nµy, cã thÓ th­¬ng l­îng ®­îc kh«ng?",
	"Bİ kİp nµy, ®· qua sö dông ch­a?",
	"Tr©n b¶o nµy, ®· qua sö dông ch­a?",
	"B¹ch cÇu hoµn nµy, ®· qua sö dông ch­a?",
	"KiÕm nµy, ®· qua sö dông ch­a?",
	"§ao nµy, ®· qua sö dông ch­a?",
	"Th­¬ng nµy, ®· qua sö dông ch­a?",
	"Bæng nµy, ®· qua sö dông ch­a?",
	"Phi ®ao nµy, ®· qua sö dông ch­a?",
	"Phi tiªu nµy, ®· qua sö dông ch­a?",
	"CÇm nµy, ®· qua sö dông ch­a?",
	"ThuÉn nµy, ®· qua sö dông ch­a?",
	"¸o nµy, ®· qua sö dông ch­a?",
	"Mò nµy, ®· qua sö dông ch­a?",
	"D©y chuyÒn nµy, ®· qua sö dông ch­a?",
	"Hé uyÓn nµy, ®· qua sö dông ch­a?",
	"NhÉn nµy, ®· qua sö dông ch­a?",
	"Ngäc béi nµy, ®· qua sö dông ch­a?",
	"Giµy nµy, ®· qua sö dông ch­a?",
	"Ngùa nµy, ®· qua sö dông ch­a?",
	"Phi phong nµy, ®· qua sö dông ch­a?",
	"Thñy tinh nµy, ®· qua sö dông ch­a?",
	"Tinh hång b¶o th¹ch nµy, ®· qua sö dông ch­a?",
	"Ta ®· chuÈn bŞ ®ñ tiÒn!",
	"Cã thÓ giao dŞch ch­a?",
	"Ng­¬i cã biÕt ®©y lµ g×?",
	"Ng­¬i b¸n bİ kİp nµy, gi¸ bao nhiªu vËy?",
	"Ng­¬i b¸n tr©n b¶o nµy, gi¸ bao nhiªu vËy?",
	"Ng­¬i b¸n b¹ch cÇu hoµn nµy, gi¸ bao nhiªu vËy?",
	"Ng­¬i b¸n kiÕm nµy, gi¸ bao nhiªu vËy?",
	"Ng­¬i b¸n ®ao nµy, gi¸ bao nhiªu vËy?",
	"Ng­¬i b¸n th­¬ng nµy, gi¸ bao nhiªu vËy?",
	"Ng­¬i b¸n bæng nµy, gi¸ bao nhiªu vËy?",
	"Ng­¬i b¸n phi ®ao nµy, gi¸ bao nhiªu vËy?",
	"Ng­¬i b¸n phi tiªu nµy, gi¸ bao nhiªu vËy?",
	"Ng­¬i b¸n cÇm nµy, gi¸ bao nhiªu vËy?",
	"Ng­¬i b¸n thuÉn nµy, gi¸ bao nhiªu vËy?",
	"Ng­¬i b¸n ¸o nµy, gi¸ bao nhiªu vËy?",
	"Ng­¬i b¸n mò nµy, gi¸ bao nhiªu vËy?",
	"Ng­¬i b¸n d©y chuyÒn nµy, gi¸ bao nhiªu vËy?",
	"Ng­¬i b¸n hé uyÓn nµy, gi¸ bao nhiªu vËy?",
	"Ng­¬i b¸n nhÉn nµy, gi¸ bao nhiªu vËy?",
	"Ng­¬i b¸n ngäc béi nµy, gi¸ bao nhiªu vËy?",
	"Ng­¬i b¸n giµy nµy, gi¸ bao nhiªu vËy?",
	"Ng­¬i b¸n ngùa nµy, gi¸ bao nhiªu vËy?",
	"Ng­¬i b¸n phi phong nµy, gi¸ bao nhiªu vËy?",
	"Ng­¬i b¸n thñy tinh nµy, gi¸ bao nhiªu vËy?",
	"Ng­¬i b¸n tinh hång b¶o th¹ch nµy, gi¸ bao nhiªu vËy?",
	"Ai muèn ®æi bİ kİp nµy kh«ng?",
	"Ai muèn ®æi tr©n b¶o nµy kh«ng?",
	"Ai muèn ®æi b¹ch cÇu hoµn nµy kh«ng?",
	"Ai muèn ®æi kiÕm nµy kh«ng?",
	"Ai muèn ®æi ®ao nµy kh«ng?",
	"Ai muèn ®æi th­¬ng nµy kh«ng?",
	"Ai muèn ®æi bæng nµy kh«ng?",
	"Ai muèn ®æi phi ®ao nµy kh«ng?",
	"Ai muèn ®æi phi tiªu nµy kh«ng?",
	"Ai muèn ®æi cÇm nµy kh«ng?",
	"Ai muèn ®æi thuÉn nµy kh«ng?",
	"Ai muèn ®æi ¸o nµy kh«ng?",
	"Ai muèn ®æi mò nµy kh«ng?",
	"Ai muèn ®æi d©y chuyÒn nµy kh«ng?",
	"Ai muèn ®æi hé uyÓn nµy kh«ng?",
	"Ai muèn ®æi nhÉn nµy kh«ng?",
	"Ai muèn ®æi ngäc béi nµy kh«ng?",
	"Ai muèn ®æi giµy nµy kh«ng?",
	"Ai muèn ®æi ngùa nµy kh«ng?",
	"Ai muèn ®æi phi phong nµy kh«ng?",
	"Ai muèn ®æi thñy tinh nµy kh«ng?",
	"Ai muèn ®æi tinh hång b¶o th¹ch nµy kh«ng?",


}

SimCityChat.chatCollectionFight = {
	"Ngon nhµo v«!",
	"§­êng nµy do ta më!",
	"Mau ®ãng tiÒn b¶o kª!",
	"Cho xin tİ b¸nh m×!",
	"A th»ng nµy l¸o!",
	"Th»ng nµo d¸m ®¸nh tao!",
	"§øa nµo c¾n lĞn «ng!",
	"Nguy hiÓm! Ch¹y lÑ!",
	"Mµy h¶ nhãc!",
	"§øa nµo d¸m qua ®©y kiÕm ¨n!",
	"Anh em ®©u x«ng lªn !",
	"Hèt nã!",
	"Trªn ®êi nµy kh«ng cã thuèc hèi hËn!",
	"Qu¸nh chÕt cô mµi",
	"Cmm",
	"§İt t nÌ, c¾n ®i",
	"Anh ¬i, nã qu¸nh em",
	"Móc!",
	"Th»ng nµy l¸o",
	"ChÕt mµi víi anh",
	"CóT",
	"Kh«ng cÇn nãi nhiÒu!",
	"D¸m mãc lèp tau h¶",
	"Tau thİch, mµi lµm g× tau?",
	"Ngon th× kĞo c¶ bang mµi ®Õn ®©y",
	"Mµi th¾ng ®­îc anh sao?",
	"İ da! Sî qu¸ c¬!",
	"Tr©u vl",
	"HÊp nã",
	"§¹i ca, tha em",
	"Tha m¹ng",
	"Ch¾c tau sî",
	"Bè chÊp c¶ hä nhµ mµi",
	"D¸m giµnh g¸i víi bè",
	"ChÕt nÌ",
	"Xem chiªu!",
	"BiÕt bè mµi lµ ai kh«ng",
	"Xuèng ®Şa ngôc ®i",
	"Nµy thi c¾n",
	"Bá tËt nghe ch­a",
	"Thİch th× cø nhİch",
	"Thİch th× chiÒu",
	"KS = ®å cmn s¸t",
	"Th»ng nµy l¸o",
	"Ngu mµ cßn nguy hiÓm",
	"Qu¸nh tao h¶ m¹i",
	"Bít nghe ch­a",
	"L¸o nha l¸o nh¸o",
	"Nhí mÆt tao nghe ch­a",
	"Lµm g× nhau?",
	"ThiÕn nã!",
	"§­êng nµy lµ do ta më",
	"Mét lêi kh«ng hîp, khai lµm",
	"Bµy ®Æt nµy nä",
	"Sèng cho tö tÕ vµo",
	"M×nh anh chÊp hÕt",
	"Gµ!",
	"§Ëp vµo mÆt",
	"§õng cã chäc tao",
	"§Şnh mÖnh",
	"§å s¸t!",
	"Coi chõng tao µ",
	"§õng Ğp ta",
	"§õng cã giìn mÆt",
	"YÕu mµ cßn ra giã",
	"Ta kh«ng vµo ®Şa ngôc, ai d¸m vµo?",
	"Anh mµi thİch",
	"Råi sao?",
	"Nµy th× qu¸nh em tao",
	"§õng nãi n÷a",
	"ChÊp 10 th»ng nh­ mµi",
	"SÏ dïng m¹ng cña m×nh ®æi m¹ng cña h¾n",
	"§¸nh phñ ®Çu, kh«ng cho ®Şch kŞp ph¶n øng",
	"ThËp tö v« sinh",
	"Cßn kĞm rÊt xa",
	"Ng­¬i lµ rôt ®Çu « quy",
	"Ch­a hÒ thua ai",
	"Kh«ng d¸m lã ®Çu",
	"ThËt béi phôc",
	"§Õn! TiÕp tôc!",
	"Kh«ng d¸m lªn tiÕng?",
	"Qu¸ mÑ nã quû dŞ",
	"Ra luyÖn 1 chót a",
	"Ngu xuÈn",
	"Kim c­¬ng bÊt ho¹i",
	"Cµng ®¸nh cµng thuËn tay",
	"Kh«ng chØ mét lÇn ¨n thiÖt thßi",
	"Kh«ng thÓ chèng l¹i",
	"Kh«ng cã chót nµo ®au ®ín",
	"Ai chŞu, ai khã chŞu?",
	"§¹o h÷u, n¾m ®Êm cña ta cøng h¬n",
	"VÉn lµ kh«ng ng¨n ®­îc b­íc tiÕn cña h¾n",
	"Ng­¬i, chäc giËn ®Õn ta",
	"Kh«ng thÌm ®Ó ı",
	"ChØ míi th¨m dß",
	"Ta cßn ch­a ®éng toµn lùc",
	"QuyÒn ch­ëng va ch¹m",
	"Ng­¬i vÉn lµ s©u kiÕn",
	"Uy lùc còng rÊt b¸ ®¹o",
	"Trùc tiÕp ®­a vµo Quû M«n Quan",
	"Døt kho¸c còng l­u lo¸t",
	"Kh«ng ph¶i tÊt c¶ ®Òu lµ phÕ vËt",
	"Gµo vang déi, kh«ng cã g× dïng",
	"RÊt lµ chãi m¾t!",
	"Con hµng nµy tõ ®©u x«ng tíi",
	"Ng­¬i sÏ chÕt rÊt thª th¶m",
	"Chèng ®ì!",
	"ThËt cßn sèng",
	"Ng­¬i ®o¸n kh«ng sai",
	"§¸nh cho thiªn b¨ng ®Şa liÖt",
	"Ng­¬i nhËn ra ta",
	"§øng còng ko v÷ng",
	"A!",
	"Trë vÒ",
	"Kh«ng sî bŞ ®¸nh chÕt",
	"Cßn tèt?",
	"Ai sî ai",
	"Muèn ng­¬i 1 chót huyÕt",
	"§îi ng­¬i rÊt l©u",
	"CËy m¹nh a",
	"Cïng nhau lªn ®i",
	"Kh«ng ph¶i trß ®ïa!",
	"Trß vui kÕt thóc",
	"Cßn ch­a ®· ngøa",
	"ë ®©u ra lùc l­îng",
	"V¸n nµy ng­¬i thua",
	"Coi lµ thËt b¸ ®¹o",
	"Ch­a h¼n lµ h¾n ®èi thñ!",
	"§Ønh phong nhÊt 1 quyÒn",
	"Ta nãi qua, ng­¬i kh«ng diÖt ®­îc ta",
	"Ng¨n kh«ng ®­îc h¾n!",
	"1 kiÕm tiÕp 1 kiÕm",
	"1 ®ao tiÕp 1 ®ao",
	"1 th­¬ng tiÕp 1 th­¬ng",
	"1 c«n tiÕp 1 c«n",
	"4 ph­¬ng 8 h­íng ®Òu cã ®Şch",
	"MÆt mòi cña ng­¬i kh«ng ph¶i b×nh th­êng lín",
	"Nh­ 1 côc ®¸ mµi ®ao",
	"Kh«ng thÓ ®ïa giìn",
	"§Õn chÕt ®Òu lµ phiÒn muén",
	"Ng¾m qu¸ chuÈn",
	"Ch¹y? C¸i nµo ch¹y?",
	"Kh«ng d¸m khinh th­êng",
	"Søc m¹nh cÊm kŞ bay móa",
	"Kh«ng d¸m nãi nh¶m",
	"§Òu ®¸ng sî nh­ vËy sao",
	"H¬n ph©n n÷a sÏ chÕt",
	"Kh«ng cho ng­¬i thë dèc c¬ héi",
	"Khã gÆp ®­îc 1 c¸i l¹c ®µn",
	"§Õn ®¸nh a",
	"§¹i triÓn thÇn uy",
	"Lµ ai ®Òu v« dông",
	"Mét ch­ëng th­êng th­êng kh«ng cã g× l¹",
	"NhÊt kiÕm tr¶m ®o¹n",
	"Ng­¬i ®æi ı?",
	"Ng­¬i uy hiÕp ta",
	"Kh«ng d¸m khinh th­êng",
	"L«i ®×nh 1 kİch",
	"Nh×n ra m¸nh khãe",
	"RÊt tèt",
	"1 ch­ëng vç to¸i",
	"Mét kiÕm mét c¸i",
	"Còng qu¸ dÔ dµng",
	"§¸nh ng­¬i thµnh c¸m",
	"T×m ng­êi ph¸t tiÕt",
	"Kh«ng d¸m chiÕn?",
	"Cè ı, ng­¬i chİnh lµ cè ı",
	"Kia lµ s¸t c¬",
	"Ng­¬i cã thÓ ngËm miÖng kh«ng",
	"Cùc kh«ng an phËn",
	"ThËt cã mét chót kh«ng chŞu nçi",
	"SÏ sím kÕt thóc",
	"§õng véi, cßn ch­a xong",
	"Ng­îc l¹i lµ tèt",
	"Kh«ng ®¬n gi¶n nh­ vËy",
	"Mèt chØ khai vŞ",
	"Hñy thiªn diÖt ®Şa c«ng ph¹t",
	"Ai ®Õn ®Òu v« dông",
	"§»ng sau cßn cã",
	"Ta kh«ng cã ®Şch thñ",
	"ChiÕn lùc gi¶m bít ®i nhiÒu",
	"TuyÖt ®èi chiÕm th­îng phong",
	"BÊt tö bÊt diÖt lùc l­îng",
	"Qu¶ nhiªn kh«ng tÇm th­êng",
	"B¸ thiªn tuyÖt ®Şa a",
	"1 ®Çu tuyÖt lé",
	"TÜnh ®Õn ®¸ng sî",
	"Trong m¾t ®Òu kh¾c t¬ m¸u",
	"Ta kh«ng b»ng ng­¬i",
	"Ng­¬i lËt ®æ ta nhËn biÕt",
	"ChÊn kinh ng­¬i thñ ®o¹n",
	"Ng­¬i thËt sù nghŞch thiªn",
	"ThËt lµ ®¸ng sî",
	"Dïng ng­¬i hiÕn tÕ",
	"TrÊn!",
	"Kh«ng biÕt x¶y ra chuyÖn g×",
	"Cam nguyÖn lµm kia qu©n cê",
	"Xem ng­¬i sî",
	"Cã chót ho¶ng hèt",
	"Kh«ng thÓ nãi?",
	"Uy ¸p thËt ®¸ng sî",
	"Mµy ph¶i tr¶ gi¸",
	"T¸n cho bép tay nÌ",
	"Anh thø 2 th× ai thø nhÊt",
	"Heo löa xong v« ch¶o",
	"Bãp dzó long tr¶o thñ",
	"Xem chiªu nÌ",
	"Kh«ng ®¸nh mÆt",
	"Buån n«n ghª",
	"µ h¸",
	"Qu©n tö ®éng thñ kh«ng ®éng khÈu",
	"Qu©n tö ®éng khÈu kh«ng ®éng thñ",
	"Chóng ta kh«ng thuéc vÒ nhau",
	"Chóng ta kh«ng lµ cña nhau",
	"Giê em hèi hËn ch­a",
	"§å c¸i thø ngu",
	"å thÕ µ",
	"D¸m ph¶n béi ta",
	"Ng­¬i gan l¾m",
	"§å thá ®Õ",
	"ChØ cÇn mét chiªu",
	"Ph¶i r¸ng xİu n÷a",
	"§å s©u kiÕn",
	"Thø gièng «n",
	"Nh·i ranh",
	"Cho ta diÖt",
	"Thõa dŞp bÖnh, ®ßi m¹ng ng­¬i",
	"Nî m¸u ph¶i tr¶ b»ng m¸u",
	"Ra lÉn vµo, ®Òu ph¶i tr¶ gi¸",
	"Ta kh«ng ngu",
	"Tû thİ kh«ng",
	"Ng­¬i thËt lîi h¹i",
	"Vò khİ cña ng­¬i xŞn qu¸",
	"Da mÆt ng­¬i thËt dµy",
	"Nhøc hÕt c¶ trøng ®©y nµy",
	"§øng im ®ã cho ta",
	"Ngon th× ®¸nh n÷a ®i",
	"¥ k×a?",
	"§õng dõng l¹i",
	"QuyÕt kh«ng ®Çu hµng",
	"D¸m nghŞch ta",
	"NghŞch lµ chÕt",
	"Cho ng­¬i 1 c¸i th«ng kho¸i",
	"Cho ta 1 c¸i thèng kho¸i",
	"Chõa nghe ch­a",
	"Tæ t«ng 18 ®êi nhµ ng­¬i",
	"Gi¸c ngé ®i",
	"C¸i thø g×",
	"CÈn thËn",
	"Coi chõng",
	"¡n ta 1 ®ao",
	"Qu©n tö tr¶ thï, 10 n¨m kh«ng muén",
	"Ta cÇn mét c©y th­¬ng míi",
	"Ta cÇn mét c©y kiÕm míi",
	"Ta cÇn mét phi ®ao míi",
	"Ta cÇn mét c©y c«n míi",
	"Ta cÇn mét vò khİ míi",
	"§ao cña ta mÎ hÕt råi",
	"1 chiªu tuyÖt mÖnh",
	"MÖt chÕt ®i ®­îc",
	"Sèng ®Õn b©y giê ®· lµ kú tİch",
	"Ta sÏ kh«ng ng· xuèng",
	"Ta sÏ kh«ng tha cho ng­¬i",
	"§Çu hµng ®i",
	"Ng­¬i ch¹y kh«ng tho¸t a",
	"Kh«ng ®­êng vÒ råi",
	"MÑ nã chø",
	"Tøc qu¸ mµ",
	"§ï mĞ",
	"TÈn nhau ®ª",
	"Cã chót phÊn khëi",
	"Kh«ng sai",
	"§Õn lóc råi",
	"Ng­¬i chê ®ã, ta gäi ®Ö",
	"VËn mÖnh ta lµ do ta n¾m gi÷",
	"Kh«ng cã löa sao cã khãi",
	"HËn a!",
	"NÕu biÕt tr­íc th× ®õng cã lµm",
	"Ta kh«ng xong råi",
	"Ch¾c kh«ng qua næi con tr¨ng nµy",
	"Ng­¬i tù s¸t ®i",
	"Thµ chÕt chø kh«ng chŞu nhôc",
	"§å së khanh",
	"Ng­¬i d¸m qua cÇu rót v¸n a",
	"Ta thu thËp ng­¬i",
	"PhÇn lÔ nµy ng­¬i cã thİch",
	"Ng­¬i thËt ng­u bøc a",
	"Ta lµ c¸i mang thï ng­êi",
	"Ta sÏ d¹y ng­¬i c¸ch lµm ng­êi",
	"ThËt lµ nghiÖp ch­íng",
	"NghiÖt sóc",
	"Th¾ng ta, dÔ vËy sao",
	"§­êng ®­êng lµ nam nhi, sî sao?",
	"TiÖn nh©n, ng­¬i c¸i tiÖn nh©n",
	"Siªu qu©n b¹t tôy a",
	"§å gian lËn",
	"D¸m c«ng b»ng 1 trËn chiÕn?",
	"TiÕp ta 1 chiªu!",
	"Qua 3 chiªu kh«ng?",
	"Trong 10 chiªu, tÊt b¹i ng­¬i",
	"Nùc c­êi thËt",
	"Ng­¬i giÕt kh«ng ®­îc ta",
	"Ta giÕt kh«ng ®­îc ng­¬i?",
	"Ta kh«ng thÓ thua ®­îc",
	"å vËy sao",
	"å thÕ µ",
	"Nhôc mÆt ch­a?",
	"Nhôc nh·, thËt lµ nhôc nh·",
	"Ta khi ng­¬i, th× sao?",
	"§õng hßng ch¹y trèn",
	"Th¾ng hay b¹i, ch­a biÕt ®­îc",
	"Cí sao l¹i qu¸nh ta",
	"Ng­¬i thËt ®éc ¸c",
	"M¹ng ng­¬i, ta lÊy",
	"MiÖng ng­¬i thËt lµ tiÖn",
	"Ta thay ng­¬i hæ thÑn",
	"Kh«ng sî ng­¬i",
	"§õng cã nãi nh¶m n÷a",
	"§Ó xem cã ai cøu ®­îc ng­¬i kh«ng",
	"Th¾ng ta, vËt nµy lµ cña ng­¬i",
	"VËt nµy vèn kh«ng thuéc vÒ ng­¬i",
	"Cøu, cøu ta a",
	"Cã gan th× ®õng ch¹y",
	"Nãi nhiÒu qu¸",
	"§Ëp ph¸t chÕt lu«n",
	"§ïa víi anh µ",
	"Ng­¬i kh«ng thÓ so s¸nh víi ta",
	"Dông tèc bÊt ®¹t",
	"Cø tõ tõ",
	"ThËt b¸ ®¹o",
	"TÊt c¶ lµ do ng­¬i",
	"Dõng tay l¹i",
	"Muèn n÷a kh«ng",
	"Ng­¬i thËt nham hiÓm",
	"Tõ bá ®i",
	"Ta kh«ng sai",
	"Ta kh«ng tin",
	"Hù hù",
	"Xay da da, cµ na xİ môi",
	"§õng gi¶ vê n÷a",
	"ThËt bi th¶m",
	"§õng nh×n ta",
	"Ng­¬i gan ®Êy",
	"Gan ng­¬i thËt mËp",
	"Ngµy sau tÊt diÖt ng­¬i",
	"YÕu cßn ra giã",
	"§Ó xem ai lîi h¹i h¬n",
	"Ta ng­u hay ng­¬i ng­u",
	"Ng­¬i kh«ng vong th× ta vong",
	"Hù!",
	"§au qu¸!",
	"Toang råi",
	"May qu¸ x¸",
	"Ng­¬i chÕt kh«ng thÓ nghi ngê",
	"Th¾ng b»ng niÒm tin µ",
	"Ng­¬i ®iªn thËt råi",
	"Kh«ng ph¶i do ng­¬i yÕu, mµ lµ ta qu¸ c­êng",
	"QuyÕt kh«ng hèi hËn",
	"Ng­¬i tay to hay ta tay to",
	"§Ó m¹ng ng­¬i l¹i",
	"M¹ng ®æi m¹ng",
	"M¹ng ®Òn m¹ng",
	"Cã thï tÊt b¸o",
	"§¸nh ch­a thèng kho¸i",
	"Cã thµnh ma còng kh«ng bá qua",
	"Ta sÏ thay huynh ta b¸o thï",
	"Ng­¬i kh«ng ®¸ng lµ ta huynh ®Ö",
	"M¹ng ng­¬i tÊt lµ cña ta",
	"Nhí mÆt ta ®ã",
	"§å khèn n¹n",
	"Ng­¬i lµ ta thiªn ®Şch",
	"Ta cã høng thó víi ng­¬i",
	"Trång rau 18 n¨m, ®Ó råi cho heo ñi",
	"Ng­¬i d¸m ®¸nh ta",
	"1 m×nh ng­¬i, kh«ng ®ñ ta ®¸nh",
	"Cña ng­¬i lµ cña ta",
	"ThiÖn tay, thiÖn tay",
	"Lßng tham sÏ giÕt ng­¬i",
	"§Êy kh«ng ph¶i lµ sù thËt",
	"Tin hay kh«ng tïy ng­¬i",
	"Dõng tay l¹i a",
	"B×nh sa l¹c nh¹n, chæng m«ng ra sau",
	"T­ thÕ nµy h¬i k× l¹",
	"Bèi rèi qu¸",
	"T¹m nghØ 2 phót",
	"Ng­¬i sao l¹i m¹nh nh­ vËy",
	"ChuyÖn ng­¬i nãi thËt nùc c­êi",
	"Quay ®Çu lµ bê, suy nghÜ l¹i ®i",
	"ı ta ®· quyÕt, kh«ng thÓ thay ®æi",
	"Ng­¬i lµ ®å vong ¬n phô nghÜa",
	"§ã lµ lçi cña ta",
	"B¹i ta, mÆc ng­¬i xö lı",
	"Th¾ng ng­¬i, ng­¬i lµ cña ta",
	"Ng­¬i b¹i, theo ta ®i",
	"Ng­¬i cßn non vµ xanh l¾m",
	"Nî cha, con tr¶",
	"Cha lµm, ta chŞu",
	"Kh«ng ph¶i xo¾n",
	"C­îc ng­êi hay c­îc m¹ng",
	"M¹ng ng­¬i, kh«ng ®¸ng gi¸",
	"H¬n nhau, chØ nhÊt chiªu",
	"Ng­¬i luyÖn c«ng thªm 10 n¨m n÷a ®i",
	"Ng­¬i kh«ng ®ñ t­ c¸ch",
	"Ta ®· cã ng­êi kh¸c",
	"Ta yªu ng­¬i, v× sao l¹i ph¶n béi",
	"ThËt muèn kh«ng chÕt kh«ng th«i?",
	"Ng­¬i cã t­ c¸ch ®ã sao",
	"§õng ®Ó c¸ chÕt l­íi r¸ch",
	"Ta vµ ng­¬i ®ång quy ­ tËn",
	"TrËn chiÕn nµy sÏ më ra kû nguyªn míi",
	"BÊt ngê thËt",
	"Thêi ®¹i nµy lµ cña ta",
	"Thay mÆt ®¹i ca, ta tr¶m ng­¬i",
	"NhÊt ®Şnh chĞm ng­¬i",
	"Tù kÕt liÔu ®i",
	"§õng n»m m¬",
	"Ng­¬i tØnh l¹i ®i",
	"§õng ®Ó ta ph¶i ra tay",
	"Ng­¬i ®iªn thËt råi",
	"TrËn chiÕn nµy nªn kÕt thóc",
	"Ta chØ cã thÓ nãi lêi xin lçi",
	"Ng­¬i qu¸ xem th­êng ta råi",
	"Xem th­êng ng­¬i",
	"Nghiªm träng ®¸nh gi¸ thÊp ng­¬i a",
	"Lµ ta qu¸ xem träng ng­¬i",
	"Kh«ng biÕt tr©n quı tİnh m¹ng",
	"M¹ng ta kh«ng thuéc vÒ ng­¬i",
	"§õng m¬ t­ëng n÷a",
	"Ta cho ng­¬i thèng kho¸i",
	"HiÓu chuyÖn ®Õn ®au lßng",
	"Chóng ta cã thï giÕt cha sao",
	"Cã thï sao?",
	"Sao l¹i ®¸nh ta",
	"Tha thiÕu nî ng­¬i h¶",
	"§õng hßng tho¸t",
	"§­a tiÒn b¶o kª ®©y",
	"§¸nh nhau c­îc mÖnh",
	"Ta th­ëng thøc ng­¬i",
	"§¸nh hay l¾m",
	"Tíi, tíi a",
	"H«m nay ng­¬i tèt chø?",
	"Thµ chÕt vinh h¬n sèng nhôc",
	"§Êm vµo mÆt mi",
	"MÖt ch­a?",
	"Bë c¶ h¬i tay",
	"Dõng l¹i a, ta ®Çu hµng",
	"Cãc cã sî",
	"M¹nh cã chót ngoµi dù kiÕn",
	"Kh«ng qu¸nh n÷a, kh«ng qu¸nh n÷a",
	"Qu¸nh a, ngon qu¸nh a",
	"Cha ta lµ t­íng qu©n",
	"Tû ta lµ hoµng hËu",
	"Qu©n tö ph¹m ph¸p, xö nh­ thø d©n",
	"TiÒn tr¶m hËu tÊu",
	"Ng­¬i cã n¨ng lùc ®ã sao",
	"Ta cã n¨ng lùc ®ã",
	"Ta kh«ng quan t©m",
	"Ta kh«ng høng thó ®¸nh víi ng­¬i",
	"§õng nh©y n÷a",
	"Ng­¬i ®· hµi lßng",
	"Võa lßng ng­¬i ch­a",
	"Hèi hËn còng mu«n råi",
	"Tha cho ta a",
	"Bí ng­êi ta, qu¸nh ng­êi",
	"Bí ng­êi ta, cøu",
	"Kh«ng ai cã thÓ cøu ng­¬i",
	"V× ng­¬i, ta sÏ hãa ¸c quû",
	"Ta m¹nh h¬n ng­¬i",
	"§å yÕu ®uèi",
	"Th¾ng thua lµ chuyÖn b×nh th­êng",
	"Ta kh«ng cÇu danh väng",
	"Cót ra ®©y",
	"Xa ta ra",
	"Cót khái ®©y",
	"Ta sÏ hñy diÖt ng­¬i",
	"Ng­¬i thö xem",
	"Ng­¬i kh«ng biÕt nhôc µ",
	"Ta sÏ kh«ng tha cho ng­¬i",
	"Ta sÏ kh«ng bá qua",
	"Giái th× cø c¾n",
	"¡n tao ®i",
	"E hÌm!",
	"B¸o øng a",
	"Muèn mang ng­êi ®ã ®i, tr­íc b¹i ta",
	"Kh«ng cÇn ph¶i gi¶i thİch",
	"§· hiÓu",
	"§¸nh tr­íc nãi sau",
	"ChØ giái vâ måm",
	"Cã thÓ ng­¬i m¹nh h¬n ta",
	"Phôc hay kh«ng phôc",
	"Hµng hay kh«ng",
	"CÇu b¹i mét lÇn",
	"Ta ch­a bao giê sî ai",
	"Ta ch­a ng¸n 1 ai",
	"§êi nµy ta chØ b¹i 1 lÇn",
	"H¾n nhËp ma råi",
	"M¹ng ta bëi ta, kh«ng do trêi",
	"Ta phôc! Ta phôc a!",
	"Vâ c«ng c¸c h¹ thËt cao th©m",
	"Th©m kh¶ m¹c tr¾c a",
	"Long cã v¶y ng­îc, ng­¬i ch¾c ch¾n ph¶i chÕt",
	"ChÕt kh«ng ph¶i lµ ta, mµ lµ ng­¬i",
	"Kh«ng chê ®­îc n÷a",
	"Ng­¬i ta bÊt ph©n th¾ng b¹i",
	"Kh«ng thÓ th¾ng ®­îc h¾n",
	"NhÊt ®Şnh ph¶i th¾ng",
	"Ta thua, t«ng m«n sÏ diÖt",
	"T«ng m«n ta sÏ kh«ng tha cho ng­¬i",
	"Tíi chÕt ta còng kh«ng quªn",
	"Ngµy nµy 10 n¨m tr­íc, ng­¬i diÖt ta c¶ nhµ",
	"GiÕt a!",
	"B¹i ta, phãng ng­¬i ng­êi th©n",
	"Ng­êi cña ng­¬i, trong tay ta",
	"§å bØ æi",
	"Oan gia nªn gi¶i, kh«ng nªn kÕt",
	"Ta ®©y mét thÕ anh danh, ®· hñy",
	"Néi lùc cña ng­¬i ®· hÕt, kÕt thóc th«i",
	"ChØ lµ míi lµm nãng ng­êi",
	"Tù g©y nghiÖt, kh«ng thÓ sèng",
	"Cã ng­êi nhê ta giÕt ng­¬i",
	"Muèn chĞm muèn giÕt, tïy ı",
	"Ta ®©y m¹nh hay yÕu",
	"Ng­¬i thËt m¹nh",
	"M¹nh ®­îc yÕu thua",
	"Trai cß ®¸nh nhau, ng­ «ng h­ëng lîi",
	"Ng­¬i chÕt, ®ã vÜnh viÔn lµ bİ mËt",
	"1 ch÷: CHIÕN",
	"§Õn 1 ng­êi, giÕt 1 ng­êi",
	"§å l× lîm",
	"T¹i sao ng­¬i l¹i biÕt chiªu thøc Êy",
	"T¹i sao ng­¬i l¹i biÕt chuyÖn ®ã",
	"Râ rµng ng­¬i yÕu h¬n ta",
	"Kh«ng ®µnh lßng a",
	"Ng­¬i d¸m khi nhôc muéi ta",
	"Ng­¬i ®· thay ®æi råi",
	"Ng­¬i kh«ng cßn lµ ng­¬i n÷a",
	"Trang c¸i bøc",
	"Tõng mét thêi, chóng ta lµ huynh ®Ö",
	"§¸nh ®i",
	"Ta ®· ®i tr­íc ng­¬i mét b­íc",
	"ThÕ giíi nµy kh«ng dµnh cho kÎ yÕu",
	"Ng­¬i tr¸ch ta sao",
	"H·y x­ng tªn ng­¬i ra",
	"Sña lín lªn",
	"Sña n÷a ®i",
	"Ng­¬i còng chØ lµ con tèt trªn bµn cê",
	"Ai th¾ng ai thua, ch­a biÕt ®­îc",
	"VËt Êy nhÊt ®Şnh thuéc vÒ ta",
	"Ng­¬i kh«ng cã cöa",
	"Lµm mµu n÷a ®i",
	"Lßng tham ®· che mê lİ trİ cña ng­¬i",
	"Cã chuyÖn sao?",
	"Ng¨n c¶n h¾n",
	"Tõ khi chia tay ®Õn giê kh«ng cã vÒ g× chø",
	"Cã chuyÖn sao?",
	"ChuyÖn g×?",
	"Ch­ëng võa råi kh«ng tÖ",
	"Ng­¬i còng kh«ng tÖ",
	"ThËt b¸ khİ",
	"Ng­¬i m¹nh, ta m¹nh h¬n",
	"ChÊp ng­¬i mét tay",
	"Cho ng­¬i qu¸nh tr­íc 3 chiªu",
	"M¹nh nh­ chã",
	"M¹nh nh­ cha ng­¬i cßn kh«ng lµm g× ®­îc ta",
	"Ng­¬i gièng h¾n nh­ ®óc",
	"Sè phËn trªu ng­¬i a",
	"Kh«ng hiÓu g× hÕt vËy?",
	"Ng­¬i kh«ng ph¶i thæi",
	"X­a ®©u b»ng nay",
	"Ta ®· kh¸c x­a råi",
	"Ta ®Õn ®ßi nî",
	"Thï cò nî míi, h«m nay thanh to¸n",
	"Muéi, h·y cho ta søc m¹nh",
	"Ca, ta thay ng­¬i b¸o thï",
	"Cã gan ®¬n ®Êu",
	"Giät n­íc mµ ®ßi so víi ®¹i d­¬ng",
	"H¹t g¹o mµ ®ßi so víi nhËt nguyÖt",
	"Ta h­íng ng­¬i khiªu chiÕn",
	"Sinh tö chiÕn",
	"Ta lµ ai mµ kh«ng d¸m",
	"Kh«ng biÕt th­¬ng h­¬ng tiÕc ngäc a",
	"HiÖn t¹i ®· hiÓu sao?",
	"ThËt cøng cái",
	"Ta th©n, ®ao th­¬ng bÊt nhËp",
	"Lµm cho gän gµng vµo",
	"ThÓ hiÖn ®i",
	"Ch­ëng nµy ®ñ hung m·nh",
	"ThËt lµ s©u a",
	"KiÕm g·y ng­êi mÊt",
	"V× sao ng­¬i thËt c­êng ®¹i",
	"Thiªn h¹ nµy, ta lµ ®Ö nhÊt",
	"S¸t khİ thËt m¹nh",
	"Ng­¬i h·y ®Ó cho ta ®i",
	"KÎ nh­ ng­¬i, kh«ng ®¸ng ®Ó sèng",
	"Ng­¬i chÕt còng kh«ng ®Òn hÕt téi",
	"BiÕt sai mµ kh«ng söa",
	"Kh«ng cam lßng",
	"B¹i qu¸ th¶m liÖt",
	"Ng­¬i mau dõng tay a",
	"Kh«ng æn",
	"Kh«ng xong råi",
	"3 tuæi, tiÓu hµi nhi",
	"Ch¾c kh«ng qua khái",
	"H¾n thËt kiªn c­êng",
	"B¶n lÜnh thËt lín",
	"Ta b¹i kh«ng ph¶i do ta yÕu",
	"Lui lui",
	"Ng­¬i sÏ chÕt rÊt khã coi",
	"§å phÕ vËt",
	"§å v« dông",
	"Chu«ng tang v× ng­¬i mµ gâ",
	"R·nh qu¸",
	"§Êm lßi 2 con m¾t",
	"V« ®Şch tİn niÖm",
	"Cã chót ®¹o h¹nh",
	"Mét chiªu ph©n th¾ng b¹i ®i",
	"Kinh ng¹c sao?",
	"Cã thï tÊt b¸o",
	"Ng­¬i kh«ng b»ng h¾n",
	"Ta kh«ng ph¶i h¾n",
	"Ta lîi h¹i kh«ng",
	"D¹ng chã h×nh ng­êi a",
	"Tµi n¨ng thËt xuÊt chóng",
	"VÉn lµ ng­¬i ng­u bøc",
	"D¸m m¾ng ta",
	"§õng lµm rén",
	"Ta cã lêi muèn nãi",
	"Kh«ng cã t©m t×nh a",
	"§· l©u kh«ng gÆp",
	"§ãng cöa th¶ chã",
	"Ên ®­êng ng­¬i cã mµu ®en a",
	"Ta lîi h¹i kh«ng",
	"Ai thua lµm ch¸u trai",
	"N·o ng­¬i nhóng n­íc sao",
	"§¸ng tiÕc a",
	"H¾n lµ h¾n, ta lµ ta",
	"HÑn ngµy t¸i chiÕn",
	"H·y xem nh­ ®©y lµ mét bµi häc",
	"Mét ®êi nµy, chÕt kh«ng tiÕc",
	"Run rÈy ®i",
	"LËp tr­êng kh¸c nhau, tÊt xung ®ét",
	"Th©n ph¸p thËt nhanh",
	"Chiªu thøc thËt m¹nh",
	"Ng­¬i lîi h¹i!",
	"T¹i sao l¹i nh­ vËy",
	"Tíi qu¸ muén",
	"TiÕc nuèi sao?",
	"Ta nh­ chÕt, ng­¬i cßn nhí ®Õn ta sao",
	"Ng­¬i chÕt sÏ kh«ng ai v× ng­¬i mµ khãc",
	"Trªn tay ng­¬i lµ thÇn binh sao",
	"ThËt xin lçi, ta cÇn vËt Êy",
	"Tr¶ l¹i ngäc béi cho gia gia ta",
	"Ng­¬i cßn nhí ngµy ®ã sao",
	"Ta c¶ ®êi nµy, sèng chØ ®Ó giÕt ng­¬i",
	"DiÖu hay kh«ng diÖu",
	"Xem ®ßn s¸t thñ",
	"§ì chiªu",
	"HÌn h¹!",
	"Qu¸ m¹nh",
	"§õng Ğp ta",
	"Ta cã thÓ nhËn thua sao",
	"Th¾ng ta 1 lÇn, kh«ng cã nghÜa cã lÇn 2",
	"Cã thÓ dõng t¹i ®©y",
	"C¸c ng­¬i trªn trêi cã linh, tÊt vui mõng",
	"Sinh tö, mÖnh do trêi",
	"¸c víi tui qu¸ vËy",
	"Lµ ta",
	"Thay ®æi thËt lín",
	"ThÇn tiªn ®Õn còng kh«ng cøu ®­îc ng­¬i",
	"1 trong 2 ta ph¶i chÕt",
	"Lµ do ng­¬i h¹i ta",
	"Ta chİnh lµ hung thñ",
	"Më m¾t ra xem cho kü",
	"Sèng ph¶i thÊy ng­êi, chÕt ph¶i thÊy x¸c",
	"Ng­¬i thËt treo a",
	"Bİ mËt ı sÏ cïng ng­¬i ch«n cïng",
	"Bİ mËt Êy sÏ cïng ta ch«n cïng",
	"NÕu ng­¬i lµ ta, ng­¬i sÏ lµm thÕ nµo",
	"NÕu ng­¬i lµ ta, ng­¬i cã d¸m",
	"V× saooooo",
	"Ta thËt v« dông",
	"Ng­¬i thËt v« dông",
	"Ng­¬i kh«ng ph¶i ta",
	"Ta kh«ng ph¶i ng­¬i",
	"Tu vi cña ng­¬i kh«ng ®ñ",
	"Tu vi cña ta kh«ng ®ñ",
	"TÊt c¶ do ng­¬i mµ ra",
	"LÇn nµy lµ c¶nh c¸o",
	"Chí ®i",
	"C¬m cã thÓ ¨n bËy, lµm kh«ng thÓ lµm bËy",
	"Lóng tóng a",
	"Kh«ng thÓ l¹i nh¸o",
	"Kh«ng phôc, ®Õn chiÕn",
	"HĞ hĞ hĞ",
	"C¸i g× còng kh«ng biÕt",
	"¦ ­ ­",
	"H¶o tiÓu tö",
	"ThËt lµm ®­îc",
	"Trang bøc a",
	"Ng­¬i diÔn kŞch rÊt giái",
	"Vë kŞch nµy lµ do ta viÕt",
	"Ng­¬i thİch chø",
	"Tù t×m kİch thİch",
	"Kh«ng thÓ v­ît qua råi",
	"KiÕm tiÒn sèng qua ngµy",
	"Ng­¬i ®ang nh×n c¸i g×",
	"TuyÖt kh«ng b«i nhä tiÒn bèi uy danh",
	"Ng­¬i c¶n ®­îc ta sao",
	"Hí hí hí",
	"§õng cã cËy giµ",
	"§¹o ®øc, ng­¬i kh«ng cã",
	"HËu sinh kh¶ óy",
	"ThËt khã nuèt a",
	"Ng­¬i c¸ch xa h¾n v¹n dÆm",
	"Ng­êi kh«ng v× m×nh, trêi tru ®Êt diÖt",
	"§¸ng tiÕc thËt",
	"TriÖt ®Ó kÕt thóc",
	"Cã chót c¶m ngé",
	"TiÕc cho mét nh©n tµi",
	"Ngµy nµy n¨m sau lµ ngµy giç cña ng­¬i",
	"Cuång, ta ®Ó cho ng­¬i cuång",
	"Kh«ng ®µnh lßng nh×n th¼ng",
	"Kh«ng ®¸ng ®Ó ng­¬i lµm nh­ vËy",
	"§øng cßn kh«ng v÷ng",
	"HiÓu bao nhiªu?",
	"§¸ng ®Ó ®¸nh ®æi sao",
	"§¸ng a!",
	"§¾ng a!",
	"Mét khèi tíi",
	"§¸nh cho ng­¬i tµn phÕ",
	"Ng­¬i lµ ngu xuÈn",
	"TÊt c¶ lµ t¹i ng­¬i",
	"Ta cã lçi víi liÖt tæ, liÖt t«ng",
	"Mäi ng­êi, vÜnh biÖt",
	"Mäi ng­êi, ta ®i tr­íc 1 b­íc",
	"KiÕp sau gÆp l¹i",
	"NghiÖp ch­íng, nghiÖp ch­íng!",
	"Ta giµ råi sao",
	"ThËt ®¸ng nghi ngê",
	"§õng lõa dèi n÷a",
	"TiÓu l­u manh",
	"Cã ı tø",
	"Ng­¬i tét cïng ®ang lµm g×",
	"Thêi gian ®óng lµ kh«ng tha mét ai",
	"Hi väng a!",
	"Hång nhan häa thñy",
	"Hång nhan b¹c phËn",
	"Ta thËt hèi hËn",
	"Ta kh«ng hèi hËn",
	"Ta kh«ng thÓ chÕt",
	"ChÕt kh«ng ph¶i lµ hÕt",
	"ChÕt còng kh«ng hÕt téi cña ng­¬i",
	"ViÖc ¸c ng­¬i lµm... thiÕu sao",
	"äc äc äc",
	"õm höm",
	"GiÊu ®Çu lßi ®u«i",
	"Ng­¬i ®· bŞ ph¸t hiÖn",
	"HiÖn nguyªn h×nh ®i",
	"Ch¼ng bao giê thÊy lµm viÖc tö tÕ",
	"§¹i t¹o hãa a",
	"§å thÊt nh©n ¸c ®øc",
	"MiÖng ng­¬i thËt thèi",
	"NhÊt kiÕm ®Şnh sinh tö",
	"Ca nµy ta kh«ng cøu næi",
	"Chèng ®ì!",
	"ThËt bÖnh ho¹n",
	"Bít gµo thĞt ®i",
	"Kh«ng cã ®­êng lui",
	"HoÆc lµ thµnh, hoÆc lµ b¹i",
	"¸ch... ¸ch... ¸ch",
	"Ng­¬i d¸m tiÕn tíi?",
	"Ng­îc l¹i ta muèn thö xem",
	"Ng­îc l¹i ng­¬i thö xem",
	"Kh«ng cßn g× ®Ó nãi",
	"Kh«ng ®¸ng ®Ó nãi",
	"Vi s­ kh«ng cã ®å ®Ö nh­ ng­¬i",
	"§õng mµ",
	"Kh«ng thÓ tin ®­îc",
	"N­íc cê nµy, ta cã thÓ ®i l¹i kh«ng",
	"N­íc cê nµy kh«ng thÓ ®i l¹i",
	"Ng­¬i kh«ng cã sù lùa chän",
	"B¶n l·nh thËt lín",
	"C¸ch tèt nhÊt lµ giÕt ng­¬i",
	"ThÕ nµo l¹i nh­ thÕ",
	"Ng­¬i lµ c¸i biÕn sè, cÇn diÖt",
	"§õng ®Ó ta thÊt väng",
	"Ph¶i nh­ thÕ chø",
	"Tíi phiªn ta",
	"Qu¸ ®ñ råi",
	"Ta th¸ch ng­¬i",
	"§õng th¸ch thøc ta",
	"N¨m nµo nhÊt ®Şnh chĞm ng­¬i",
	"Sù chŞu ®ùng cña ta lµ cã h¹n",
	"§au tim qu¸",
	"NĞ ®­îc chiªu råi",
	"TÊt c¶ ®· lµ qu¸ khø",
	"Ng­¬i cßn d¸m giÊu diÕm sao",
	"Ph¸t háa råi µ",
	"T¹ch cmnr",
	"N¨ng lùc cña ng­¬i chØ thÕ sao?",
	"Cßn kh«ng ch¹y?",
	"C¸ch ng­¬i lµm lµ sai",
	"Ng­¬i chØ lµ chã s¨n",
	"ThËt kh«ng dÔ chŞu",
	"H¬n ph©n n÷a lµ chÕt",
	"§au qu¸ ®au",
	"Lùc bÊt tßng t©m a",
	"Cã thÓ",
	"T­ thÕ thËt ®Ñp",
	"H¶o chiªu",
	"Th­êng th«i... th­êng th«i",
	"Nãi nh­ thÕ nµo ®©y",
	"Cø vËy mµ ph¸t huy",
	"Chãng mÆt qu¸",
	"B©y giê míi biÕt sî sao?",
	"Ta kh«ng cam lßng",
	"H÷u t©m v« lùc",
	"LiÒu chÕt ®¸nh cuéc 1 lÇn",
	"Nh­ thÕ nµo nh­ thÕ",
	"LiÒn nh­ vËy",
	"ThËt nghŞch thiªn",
	"Thêi ®¹i nµy thËt hçn lo¹n",
	"V« ph¸p nghŞch chuyÓn",
	"¢n t×nh nµy, kiÕp sau tr¶",
	"C¸i gi¸ ph¶i tr¶ lµ qu¸ ®¾t",
	"Ng­¬i kh«ng lµm ®­îc",
	"Cã chót kh«ng chŞu ®­îc",
	"Nãng hÕt c¶ mÆt",
	"Quû dŞ thËt!",
	"Ng­¬i sÏ kh«ng thÊy ngµy mai",
	"Ng­¬i ®ang lµm c¸i g×?",
	"Mïi m¸u thËt tanh",
	"Ta thİch m¸u",
	"Hçn lo¹n kh«ng chŞu næi",
	"Mïi m¸u nãng qu¸",
	"§å m¸u l¹nh",
	"Th× ra chİnh lµ ng­¬i",
	"V× ng­¬i mµ ta mÊt tÊt c¶",
	"SÆc",
	"Ta míi chØ dïng 1 thµnh c«ng lùc",
	"Hoµi nghi nh©n sinh a",
	"GiÕt ng­¬i, chØ cÇn 1 ngãn tay",
	"Kh«ng ®óng",
	"Ng­¬i tõng nghÜ ®Õn ngµy nµy?",
	"Kh«ng sím th× muén còng kÕt thóc",
	"Ngµy nµy cuåi cïng còng ®Õn",
	"Ta khinh th­êng ng­¬i",
	"Kh«ng nh­ trong t­ëng t­îng",
	"Kh«ng ®¸ng chó ı",
	"Ng­¬i d¸m lµm ng­êi Êy buån",
	"1 m×nh ta lµ ®ñ",
	"Kinh nghiÖm chiÕn ®Êu thËt phong phó",
	"V« cïng yÕu ®uèi",
	"Ng­¬i ®¸ng lµ ®èi thñ cña ta",
	"L­êi nh¸t nãi nh¶m",
	"§· nh­ vËy, kh«ng cÇn ph¶i giÊu n÷a",
	"NghiÒn Ğp a",
	"Thùc lùc cña ng­¬i",
	"Lµm g× mµ dÔ ¨n nh­ vËy...",
	"Lµm sao?",
	"Ng­¬i thËt khã nhai",
	"Qu¸ khen... qu¸ khen",
	"Ta kh«ng tin",
	"Ta kh«ng ph¶i lµ ®èi thñ cña ng­¬i",
	"Tin hay kh«ng",
	"§· kh«ng ph¶i lµ viÖc träng yÕu",
	"Hé gi¸, hé gi¸",
	"T¹i sao c¸c ng­¬i l¹i ®øng nh×n",
	"Cã chuyÖn g× ®ã kh«ng ®óng",
	"Gi¸c ngé ch­a?",
	"Ng­¬i g¸nh kh«ng næi",
	"Muèn thö mét lÇn",
	"Ng­¬i kh«ng cßn c¬ héi",
	"ThËt c¶m ®éng",
	"§Şnh sè råi",
	"Ng­¬i ®· bá qua thêi c¬",
	"Khİ thÕ thËt bµng b¹c",
	"ThËt v« song",
	"Ta cßn l¹ g× ng­¬i",
	"Thõa n­íc ®ôc th¶ c©u",
	"Ta cã thÓ nãi mét c©u ®­îc kh«ng?",
	"Quú xuèng!",
	"Ph¶n nghŞch!",
	"Ph¶n tÆc!",
	"ThËt lµ ng«ng cuång",
	"§å ng¹o m¹n",
	"VËy th× chÕt ®i",
	"Tu vi l¹i kh«ng thÊp",
	"Ng­êi so víi ng­êi, tøc chÕt ng­êi a",
	"ThÕ cê ®· ®Şnh, kh«ng thÓ thay ®æi",
	"Cø cho lµ nh­ thÕ",
	"Ng­¬i c¸i tiÖn nh©n",
	"KÕt thóc råi!",
	"Xong!",
	"V« ¬n, béi nghÜa",
	"Tr¸nh xa ta ra",
	"Bá tay ra",
	"Ng­¬i ®ang hï däa ta sao",
	"ThÇn c¶n giÕt thÇn",
	"PhËt c¶n giÕt phËt",
	"Kh«ng cã c¸i g× gäi lµ c«ng b»ng",
	"Nh©n thÇn céng phÉn v× ng­¬i",
	"V« dông th«i",
	"Bän chuét nh¾t",
	"§å thá ®Õ",
	"Kh«ng lÏ ta sÏ chÕt t¹i ®©y sao",
	"Kh«ng may, ng­¬i ®ông ph¶i ta",
	"§¸ ph¶i tÊm s¾t råi",
	"T­ëng dÔ ¨n µ",
	"ThÊy chuyÖn bÊt b×nh, ra tay t­¬ng trî",
	"Ng­êi tèt kh«ng lµm nh­ vËy",
	"M¹nh, thËt m¹nh a!",
	"Ng­¬i kh«ng cã l­¬ng t©m",
	"L­¬ng t©m ng­¬i bŞ cÈu tha sao?",
	"TiÒn lµ tÊt c¶",
	"Ta hèi hËn råi",
	"§¸nh b¹i ng­¬i",
	"Ta c­îc lµ ng­¬i thua",
	"Yªn chİ an nghØ ®i ha",
	"Ng­¬i cßn d¸m ®Õn gÆp ta sao?",
	"Sao l¹i kh«ng d¸m",
	"Ng­¬i qu¶n kh«ng ®­îc ta",
	"Kh«ng thÓ tha thø ®­îc",
	"Kh«ng thÓ thÕ ®­îc",
	"Tøc chÕt ta",
	"Xin h·y bu«ng tha ta",
	"CÇu xin ng­¬i",
	"H·y ®Ó ta yªn"
}




-- General Helpers
function SimCityChat:getChat()
	return self.chatCollection[random(1, getn(self.chatCollection))]
end

function SimCityChat:getChatFight()
	return self.chatCollectionFight[random(1, getn(self.chatCollectionFight))]
end
