SimCityPlayerName = {}

SimCityPlayerName.data = {
"Ngôy Diªn",
"Ph¹m Tr­êng Long",
"Lôc V¨n Long",
"Hïng §×nh BËt",
"Bµnh ThiÖn",
"§Æng ThÕ X­¬ng",
"Tr­¬ng Bµo",
"H¹ng Vò",
"Tr­¬ng L­îng",
"S¸i Trung",
"L©m Ph­îng T­êng",
"Hµn H¹o",
"M· T«n",
"Hoµn Nhan X­¬ng",
"Hµn TÝn",
"H¹ Duy Tr©n",
"Niªn Canh Nghiªu",
"S¸i §×nh Kh¶i",
"Anh Bè",
"M«ng §iÒm",
"Hå ChÈn",
"§ç DuËt Minh",
"Tr­¬ng T«ng X­¬ng",
"T«n Kiªn",
"T¶ T«ng §­êng",
"Hoµn Nhan T«ng Hµn",
"Gia LuËt Së Tµi",
"L­u B¸ ¤n",
"T­ M· S­",
"Mao Tr¹ch §«ng",
"La Tr¸c Anh",
"L¹i TruyÒn Ch©u",
"D­¬ng Duyªn Chiªu",
"T«ng Tr¹ch",
"Liªu DiÖu T­¬ng",
"Lý L¨ng",
"Lý T«ng Nh©n",
"§µm Hïng",
"Hång Thõa Trï",
"Hå L©m Dùc",
"L©m VÜnh Th¨ng",
"Tr­¬ng Gi¸c",
"T«n S¸ch",
"T¹ HuyÒn",
"S¸i M¹o",
"S¸i Dôc Vinh",
"Hoa Méc Lan",
"Vò V¨n Hãa CËp",
"T¨ng C¸ch L©m ThÊm",
"M· Ph­¬ng",
"Nh¹c Chung Kú",
"NhiÖm Trô",
"S¸i Hßa",
"D­¬ng §¾c ChÝ",
"D­¬ng H¹c",
"Tr­¬ng Tù Trung",
"Chung Ly Muéi",
"Lý Tó Thµnh",
"Tõ Ho¶ng",
"T«n Vò",
"Phóc Khang An",
"M· V©n Léc",
"TrÞnh Kinh",
"H¹ HÇu Uyªn",
"H¸c Diªu Kú",
"T«n TruyÒn Ph­¬ng",
"T«n TÉn",
"Thi Lang",
"Lý Tån HiÕu",
"Nh¹c NghÞ",
"TÇn C¬ VÜ",
"TriÖu Quang NghÜa",
"Tèng NhiÖm Cïng",
"M· §¹i",
"§inh Phông",
"TÇn NhËt C­¬ng",
"§a NhÜ Cæn",
"La Vinh Hoµn",
"La Th«ng",
"Sµi Vinh",
"T­ M· H©n",
"TiÕt Nh©n Quý",
"V­¬ng TiÔn",
"Hµn ThÕ Trung",
"TrÇn NghÞ",
"L¹i H¸n Anh",
"Phµn Kho¸i",
"Cam Huy",
"§­êng ChÝnh Tµi",
"Ngao B¸i",
"Hoµng Phi B¸o",
"TrÇn Minh Nh©n",
"T¨ng Quèc Phiªn",
"L­u VÜnh Phóc",
"UÊt Tr× Cung",
"S¸i Hu©n",
"NhÜ Chu Vinh",
"Cao Kh«i Nguyªn",
"Tµo TÝnh",
"V­¬ng §¾c Léc",
"Hoµng C¸i",
"Th¹ch Thñ TÝn",
"V¨n Xó",
"Chu ThÞnh Ba",
"M«ng Ngao",
"Tµo C­¬ng Xuyªn",
"Gia LuËt H­u Ca",
"T«n LËp Nh©n",
"TriÖu V©n",
"D­¬ng Tù X­¬ng",
"H¹ HÇu §«n",
"M· Chiªm S¬n",
"Sö T­ Minh",
"Tr­¬ng T¸c L©m",
"Tiªu Phu Tø",
"§ç Phôc Uy",
"Tµo C«n",
"Khæng H÷u §øc",
"D­¬ng V¨n Qu¶ng",
"§Æng TiÓu B×nh",
"Liªu Hãa",
"Tèng HiÕn",
"Long V©n",
"§inh NhËt X­¬ng",
"Tõ H­íng TiÒn",
"L¹i Th¸p",
"Hoµng Phñ Tung",
"Bµnh Ngäc L©n",
"Ng« Béi Phu",
"Lý Nh­ Tïng",
"Ngu Do·n V¨n",
"T«n TruyÒn §×nh",
"M· ViÖn",
"Phã H»ng",
"An §øc Hinh",
"Lý ThÕ TÝch",
"Tr×nh Tri TiÕt",
"Giang B©n",
"T¹ Th¹ch",
"VÖ Thanh",
"L­u ¸ L©u",
"§æng M©n",
"T­ëng B¸ch Lý",
"Tr­ëng T«n V« Kþ",
"TrÞnh Thµnh C«ng",
"§¸o Ng¹n Chi",
"Hoa Hïng",
"V­¬ng B¶o B¶o",
"Th­îng Kh¶ Hû",
"§a §¹c",
"Phïng Ngäc T­êng",
"§a Long A",
"M· Bé Ph­¬ng",
"Lý Tån Ch­¬ng",
"L­u Bé ThiÒm",
"L· Bè",
"T­ëng Trung ChÝnh",
"L­ Thùc",
"L¹i V¨n Quang",
"Mao Nguyªn Nghi",
"L¹i ¢n T­íc",
"Lý §Þnh Quèc",
"§µm Lu©n",
"Cao Tr­êng Cung",
"UÊt Tr× Thanh San",
"Tõ ThÞnh",
"Chung Héi",
"Bµo Siªu",
"Th¹ch §¹t Khai",
"TrÇn Canh",
"Qu¸ch Tïng L©m",
"La §¹i C­¬ng",
"Lý ThÕ D©n",
"L­u B¸ Thõa",
"Vi V©n Tïng",
"A QuÕ",
"DiÖp §Ünh",
"D­¬ng H¹o",
"Tõ H¶i §«ng",
"TriÖu Xa",
"Ch­¬ng Hµm",
"Phïng Tö Tµi",
"§µn §¹o TÕ",
"Du §¹i Du",
"T­ M· Chiªu",
"Hoµng Sµo",
"Lý TÕ Th©m",
"Th¾ng B¶o",
"HÇu Qu©n TËp",
"L÷ M«ng",
"Ma Quý",
"Høa Trö",
"§æng Õ",
"Tèng NghÜa",
"TrÞnh Chi Long",
"TriÖu Khu«ng DËn",
"Ng­u Hoµnh Th¨ng",
"Tr­¬ng D­¬ng",
"Hµn Tiªn Së",
"ThiÕt HuyÔn",
"B¸ch BiÕn Quû ¶nh",
"Vâ §ang thÊt tö",
"Tr­¬ng Tam Phong",
"Thik ch¬i VD",
"Tr­¬ng V« Kþ",
"Y thiªn kiÕm",
"Tèng ViÔn KiÒu",
"NhÊt kiÕm",
"Du Liªn Ch©u",
"ThÇn kiÕm",
"Du §¹i Nham",
"Thiªn h¹ v« ®Þch",
"Tr­¬ng Tïng Khª",
"KiÕm v« t×nh",
"Tr­¬ng Thóy S¬n",
"T­ M· V« T×nh",
"¢u D­¬ng V« §Þch",
"¢n Lª §×nh",
"Thiªn ®Þa v« cùc",
"M¹c Thanh Cèc",
"§ao kiÕm v« t×nh",
"KiÕm khÝ",
"§ËpTrai§ËpKiÕm",
"Vâ §ang QuyÒn",
"Bª§ªQuÈyKiÕm",
"Hiªn viªn kiÕm",
"Vâ §ang KiÕm",
"KiÕm thÕ",
"V« §Þch ThÇn C¸i",
"¡n mµy cÇm gËy",
"Gi¸ng long",
"Tr­¬ng Qu©n B¶o",
"3 con zun",
"§· cÈu bæng",
"TiÒm Long V« Thñ",
"Rång thiªn",
"L·o C¸i",
"¡n mµy ®¹i gia",
"Thik lµm ¨n mµy",
"ThÇn long",
"Ngò Tiªn",
"ThÇn xo¸y",
"V¹n ®éc bÊt x©m",
"KÎ hót m¸u",
"Xo¸y bay tãc",
"V¹n ®éc",
"§éc v« t×nh",
"Em ch¬i 5 ®éc",
"Xo¸y tèc v¸y",
"5 §éc",
"L·o §­êng",
"Xo¸y",
"L©m TuyÕt Nh¹n",
"B¨ng hµ tan ch¶y",
"ThÇn buff",
"L©m TuyÕt",
"Siªu buff",
"Nh­ ý",
"KiÕm 3 tia",
"M­a sao b¨ng",
"Thiªn b¨ng",
"Qu¸ch T­¬ng",
"ThÝchThÞtCÇy",
"TiÓu thiÕu l©m",
"L·o S­",
"Chñ tr×",
"L·o S­ Phô",
"§¹t ma",
"Thik thiÕu l©m",
"§Çu Träc",
"§Çu Cã Tãc",
"ThÝch Mäc Tãc",
"Thik ¨n mÆn",
"ThÝch Kho¸i L¹c",
"Háa S¸t §a T×nh",
"NhÊt kÝch ph¸ thiªn",
"V­u L¹c Nh¹n",
"Löa tõ ®Þa ngôc",
"N÷ T­íng Nga",
"Lèc xo¸y",
"ChÐm giã",
"Tia chíp kinh hoµng",
"C¬n lèc v« t×nh",
"B¸c Cø §Ó Em",
"B¹chS¸t",
"Chó Cø §Ó Anh",
"Tr¶mPhong",
"Ma Long",
"Bè Cø §Ó Con",
"TöuKiÕm",
"Ch¸u Cø §Ó ¤ng",
"HuyÕt ChiÕn",
"TµnKiÕm",
"Tªn ng¾n dÔ nhí",
"NhÊtThiªn",
"Tªn dµi khã nhí",
"§i Øa quªn mang giÎ",
"NhÊt Xung Thiªn",
"NhÊtKiÕm",
"ThÊm §éc Lµ Ngñ",
"V×EmAnhMÖt",
"Thay Trêi Hµnh §¹o",
"NgÞchThiªn",
"Tæ Quèc CÇn Anh",
"MaKiÕm",
"§ang Øa L¨n Ra XØu",
"Ngèc Nh­ Con èc",
"H¾cS¸t",
"§ang XØn L¨n Ra Ngñ",
"T¶ L·nh ThiÒn",
"Nh¹c BÊt QuÇn",
"Qu¸ch KhiÕu Thiªn",
"Hoa M·n L©u",
"§oµn Dù",
"H­íng VÊn Thiªn",
"Bao TÝch Nh­îc",
"A Tö",
"Méc UyÓn Thanh",
"Mé Dung Phôc",
"D­¬ng ThiÕt T©m",
"V­¬ng Ng÷ Yªn",
"A Chu",
"Môc NiÖm Tõ",
"Lý B×nh",
"Tiªu Phong",
"LÖnh Hå Xung",
"H­ Tróc",
"NhËm Doanh Doanh",
"¢u D­¬ng Phong",
"BÊt Giíi hßa th­îng",
"Phong Thanh D­¬ng",
"Nh¹c Linh San",
"Nghi L©m",
"Liªn Qu©n",
"NhËm Ng· Hµnh",
"L­u ChÝnh Phong",
"§«ng Ph­¬ng BÊt B¹i",
"L©m B×nh Chi",
"§iÒn B¸ Quang",
"Qu¸ch TÜnh",
"NghÌonh­conmÌo!",
"Ngu nh­ c¸i lu!",
"B¸n m¸u nu«i ch¸u",
"Sãc lä gi¶m thä",
"§¹pCøtTr©yTÌLe",
"ãngM­îtNh­S­!",
"T©y ph­¬ng chiÕn b¹i",
"§ang Øa bÞ b¾n tØa",
"Qu©n Kun",
"BiÕnTh¸iThµnhThÇn",
"Nam ph­¬ng lôi b¹i",
"Trung thÇn v« b¹i",
"§«ng ph­¬ng thÊt b¹i",
"Côc cøt thÇn bÝ",
"LaHÐtTrongToaLoÐt!",
"ThÝch ThÓ HiÖn",
"B¾c ph­¬ng tù b¹i",
"XÐm V« §èi",
"KiÕm N¸t Tö Cung",
"Tr­¬ng Tam Phong",
"Du Liªn Ch©u",
"L©m TuyÕt Nh¹n",
"Du §¹i Nham",
"Háa S¸t §a T×nh",
"M¹c Thanh Cèc",
"Tr­¬ng Tïng Khª",
"§ËpTrai0§ËpKiÕm",
"L·o S­",
"L·o C¸i",
"Qu¸ch T­¬ng",
"L·o S­ Phô",
"Tr­¬ng Thóy S¬n",
"V¹n ®éc",
"Tr­¬ng Qu©n B¶o",
"Tèng ViÔn KiÒu",
"Ngò Tiªn",
"ThÝch Mäc Tãc",
"¢n Lª §×nh",
"V­u L¹c Nh¹n",
"V« §Þch ThÇn C¸i",
"ThÝch Kho¸i L¹c",
"Bª§ªQuÈyKiÕm",
"§Çu Träc",
"Xo¸y",
"L·o §­êng",
"Tr­¬ng Qu©n B¶o",
"TiÒm Long V« Thñ",
"ThÝchThÞtCÇy",
"L©m TuyÕt",
"§Çu Cã Tãc",
"5 §éc",
"TøHoµngH«n",
"LýM¹cSÇu",
"Qu¸chTòn",
"Do·nChÝLä",
"HD­îcS­",
"§µL«i",
"KiÒuDiÔm",
"TiªuS­ng",
"H¸H¸Hî",
"LôcB×nhBÌo",
"ChuB¸T«n",
"V«Ch­ëng",
"V­¬ngGiËt",
"Kh¾cT­VÖ",
"H¾c§«",
"KimTõ§iÓn",
"LýLÊnCÊn",
"HångTC«ng",
"Do·n§¹iHiÖp",
"KúDanhDanh",
"NgoanTróc",
"M·KÝnh¢n",
"KhaB¶oCh©u",
"C«ngT«nXÝch",
"D­¬ngQu¸",
"Quan §«ng",
"TrÊn Nhµ",
"H­Tróc",
"Lôc Ma",
"Qu¸ch§éng",
"Qu¸chTÜnh",
"B¾c§iÓu",
"B×nh Thiªn",
"Tø ChiÕn",
"Kh©u QuyÒn",
"Th­íng S¬n",
"MrTÌo",
"Tr×nhAnh",
"Tr×nhEm",
"§ÇuCãTãc",
"ThÝchMäcTãc",
"Bª§ªQuÈyKiÕm",
"§ÇuTräc",
"ThÝchThÞtCÇy",
"MrHiÕm",
"LïPhi",
"BÐHétTiªu",
"Bè TrÎ",
"Bè Giµ",
"Long XÝch",
"Tam Nh«ng",
"Say xØn x«ng v« hÎm",
"Mutxongdong",
"ThÇy «ng néi",
"TieuLyPhiDep",
"ChoiXongDong",
"ThÝch lµ nhÝch",
"V« ®èi",
"H¾c lµo em H¾c §iÓu",
"C¸iNåiG×ThÕ",
"Bãp vó 2xu Sê mu 2xÞ",
"Tao lµ m¹nh nhÊt",
"Kho¸i Giao hîp",
"§ang T¨m X«ng Z«Bãp",
"ChÕt mµy nÌ",
"Lç §Ýt Ch¬i Míi KhÝt",
"ThÝch ch¬i kh«ng",
"Bãp vó 5xu Mß mu 5c¾c",
"Thî söa èng n­íc",
"TrïmTK",
"Oai Nh­ Cãc",
"Mét xo¸y tãc v¸y",
"§éc Xuyªn Lç §Ýt",
"§o¹t mÖnh thÇn chïy",
"Kho¸i NghÜa Lµ ThÝch",
"ThÇn xo¸y",
"L¸ chµ bån",
"§éc nhu t×nh",
"S÷a mÑ cã ®éc",
"1 ®ao tãc v¸y",
"X«ng lªn giÕt",
"Qu©n tö ®éc",
"ãngM­îtNh­S­!",
"KiÒu thiªn ®¨ng",
"Tæ quèc cÇn Anh",
"Trïmbuff",
"Mµy thua råi",
"Bª§ªQuÈyKiÕm",
"Thay trêi hµnh ®¹o",
"DiÖt tuyÖt s­ th¸i",
"Yªu ThÇm MÑ Vî",
"Phª kh«ng t­ëng",
"§ang §¸i GÆp B¹n G¸i",
"§Çu träc vuèt keo",
"T©y ph­¬ng chiÕn b¹i",
"Qñy lÖ",
"HiÖp sÜ kh«ng ch¬i ®Ü",
"§¹i háa v­¬ng",
"Con cu huyÒn tho¹i",
"ThÝch thiÕu l©m",
"§ang bËn quay tay",
"5 ®éc",
"Ch¹y ®i ®©u",
"Bó LozDånDame",
"ThÊy anh hay kh«ng",
"HiÕp em ®i",
"Côc cøt th¬m tho",
"Sãc lä ra s÷a «ng thä",
"Cøt dÝnh bê m«i",
"VÐt m¸ng ¨n s¸ng",
"Sãclä ra s÷a«ngthä",
"ChÐm Bè NÐ",
"Tiªn ¤ng §¸ Phß",
"Chïa1cét2hét2bªn",
"Rång siªu lén",
"Chïa 1 Cét 2 Hét 2 Bªn",
"Trïm vÐt m¸ng",
"Bèng tËp t¹",
"Säc lä th©u ®ªm",
"Ch¬i hoµi kh«ng ra",
"1 nh¸t n¸t tö cung",
"§ang Øa GÆp KÎ Thï",
"§éc Nµy Y Häc Bã Tay",
"DoLaThanChuogLP",
"Con chim be bÐ",
"Mçi B÷a Hai B¸t",
"Vî chó cø ®Ó anh",
"§Ó m×nh g¸nh cho",
"Con cu be bÐ",
"Kho¸i vî th»ng b¹n",
"Côc cøt thÇn bÝ",
"Chó cø ®Ó anh",
"§i Øa quªn mang giÎ",
"Ngåi Xæm M«ng To H¼n",
"VÐt m¸ng t×m vµng",
"1 Vó NgËp Måm",
"§ang Ngñ Vî Rñ Pk",
"§Æt tªn g× ®©y",
"Hehe win nhÐ",
"C« bÐ m¾t lÐ",
"Con có cã gai",
"Lçi phÇn mÒm",
"B­ím Em Cã §éc",
"Rungmotgocgiuong",
"§Çu träc tãc dµi",
"Tªn dµi khã nhí",
"Kh«ng thÓ kÕt nèi",
"¡n Ngñ NghØ §Þt",
"¡n chuèi anh ®i",
"Anh cã khoai to",
"Bãp vÕu em ®i",
"ChuyÖn nhá mµ",
"§ang Øa bÞ b¾n tØa",
"Tôi bay gµ qu¸",
"Tªn hay qu¸",
"Tui lµ con trai",
"Chuyªn §Ëp Chã",
"Tr¸nh ra ®Ó t«i",
"BÇn t¨ng ®i ch¬i g¸i",
"XuÊt Tinh Trïng",
"B¶n S¾c Anh Hïng",
"B¾c ph­¬ng tù b¹i",
"§Çu träc 2 m¸i",
"Luis X¸ch X«V«i",
"Nhµ s­ tãc dµi",
"M¸y hÕt Pin",
"Chuèi to ngËm khái ho",
"Cóp ®iÖn råi",
"Con c«ng ®ang ngñ",
"ChÞch x· giao",
"Ngu nh­ c¸i lu!",
"V¹n ®éc",
"Trung thÇn v« b¹i",
"Tao nh­êng mµy th«i",
"Khoai to ko lo chÕt ®ãi",
"§Ó ®Êy anh lo",
"Bãp vÕu c¸i coi",
"ChuyÖn nhá th«i",
"La hÐt trong toilet",
"LaHÐtTrongToaLoÐt!",
"XuÊt tinh ®¹i ph¸p",
"Dông Trøng",
"Bè Giµ PK §Ò 3 F9",
"Xaysinxongdoham",
"ThÝchThÞtCÇy",
"SayxØnx«ngv«hÎm",
"§Çu cã tãc",
"Nam ph­¬ng lôi b¹i",
"§éc C« CÇu B¹i",
"Sî mµy qu¸",
"Mong Méc Thø Lçi",
"Kamejoko bïm",
"§Çu hµng ®i",
"Lén c¸i bê",
"§ang Øa bÞ ®¸nh lÐn",
"Qu¸ gµ",
"To §en Vµ Dµi",
"ThÝch ¨n chuèi",
"¤m Ph¶n Lao Ra BiÓn",
"1 phót ®· ra",
"MÑ B¶o Gäi Bè VÒ Solo",
"Tªn ng¾n dÔ nhí",
"Vâ L©m Ko Cã QuÇn",
"Tui tho¸t ®©y",
"XuÊt Tinh §¹i Ph¸p",
"§«ng ph­¬ng thÊt b¹i",
"Thñ D©m ThÇn C«ng",
"ThÝch ch¬i g¸i",
"L«i Cu Ra §èp",
"§ÞtVîBestie"
}


function SimCityPlayerName:getName()
    return self.data[random(1, getn(self.data))]
end